// PreToolUse(Edit|MultiEdit|Write|NotebookEdit): block direct writes to
// generated files, to supabase/applied.json and to a migration already
// applied to a hosted project. See .claude/README.md, "Hooks".

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { readInput, guard, deny, relPath, pathKey, repoRoot } from './lib.mjs';

const MIGRATIONS = 'supabase/migrations/';

/** The projects whose list in supabase/applied.json names `file`. A missing
 * or unparsable file names none, so it denies nothing. */
function appliedTo(file) {
  try {
    const applied = JSON.parse(
      readFileSync(path.join(repoRoot(), 'supabase', 'applied.json'), 'utf8')
    );
    return Object.keys(applied).filter(
      (project) =>
        Array.isArray(applied[project]) &&
        applied[project].some((n) => typeof n === 'string' && pathKey(n) === file)
    );
  } catch {
    return [];
  }
}

// Every test here runs against pathKey(rel), not rel itself: relPath() keeps
// real casing on POSIX, and a literal like 'data.json' must match regardless
// of how the caller happened to spell it - see pathKey()'s doc comment.
const DENY = [
  {
    test: (p) => p === 'data.json',
    message:
      'Blocked: data.json is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p === 'catalog.csv',
    message:
      'Blocked: catalog.csv is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('i/'),
    message:
      'Blocked: i/*.html and i/en/*.html are generated share stubs. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('en/'),
    message:
      'Blocked: en/index.html is the generated English entry document. Edit tools/build-share-pages.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('pages/') && !p.startsWith('pages/src/') && p.endsWith('.html'),
    message:
      'Blocked: pages/*.html and pages/en/*.html are generated site pages. Edit pages/src/<id>.html (Russian) or pages/src/en/<id>.html (English), then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('dist/'),
    message:
      'Blocked: dist/ is build output. Edit the source under app/src/ and run `npm run build`.'
  },
  {
    test: (p) => p === 'package-lock.json',
    message:
      'Blocked: package-lock.json is generated. Change package.json and run `npm install`.'
  },
  {
    test: (p) => p.startsWith('tests/app/snapshots/'),
    message:
      'Blocked: tests/app/snapshots/*.txt are structural goldens, regenerated by node tests/app/golden.js --update. Do not hand-edit one to make a run pass.'
  }
];

guard(() => {
  const input = readInput();
  const event = input.hook_event_name || 'PreToolUse';
  const filePath = input.tool_input && input.tool_input.file_path;
  const rel = relPath(filePath, input.cwd);
  if (rel === null) return undefined;
  const key = pathKey(rel);

  for (const rule of DENY) {
    if (rule.test(key)) return deny(event, rule.message);
  }

  if (key === 'supabase/applied.json') {
    return deny(
      event,
      'Blocked: supabase/applied.json is written by `npm run db:push` after a successful push, which the owner runs. Do not edit it by hand.'
    );
  }
  if (key.startsWith(MIGRATIONS)) {
    const projects = appliedTo(key.slice(MIGRATIONS.length));
    if (projects.length) {
      return deny(
        event,
        `Blocked: ${rel} is applied to ${projects.join(' and ')}; write a new migration instead.`
      );
    }
  }
  return undefined;
});
