// PreToolUse(Edit|MultiEdit|Write|NotebookEdit): block direct writes to
// generated files and to a migration that a remote-tracking ref holds - CI
// applies every pushed migration, so a pushed one is history. Git is the
// record; no file lists applied migrations. See .claude/README.md, "Hooks".

import { spawnSync } from 'node:child_process';
import { readInput, guard, deny, relPath, pathKey, repoRoot } from './lib.mjs';

const MIGRATIONS = 'supabase/migrations/';

/** Returns the remote-tracking refs whose tree holds
 * supabase/migrations/<file>. A repository with no remote ref, or any git
 * failure, gives none, so it denies nothing. */
function remoteRefsHolding(file) {
  const git = (args) =>
    spawnSync('git', args, { cwd: repoRoot(), encoding: 'utf8', windowsHide: true });
  const list = git(['for-each-ref', '--format=%(refname:short)', 'refs/remotes/']);
  if (list.error || list.status !== 0) return [];
  // `origin/HEAD` (short form `origin` on some git versions) is a second name
  // for a ref already listed.
  const refs = list.stdout
    .split(/\r?\n/)
    .filter((ref) => ref.includes('/') && !ref.endsWith('/HEAD'));
  return refs.filter((ref) => {
    const r = git(['cat-file', '-e', `${ref}:${MIGRATIONS}${file}`]);
    return !r.error && r.status === 0;
  });
}

// Every test here runs against pathKey(rel), not rel itself: relPath() keeps
// real casing on POSIX, and a literal like 'data.json' must match regardless
// of how the caller happened to spell it - see pathKey()'s doc comment.
const DENY = [
  {
    test: (p) => p === 'data.json',
    message:
      'Blocked: data.json is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p === 'catalog.csv',
    message:
      'Blocked: catalog.csv is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('i/'),
    message:
      'Blocked: i/*.html and i/en/*.html are generated share stubs. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('en/'),
    message:
      'Blocked: en/index.html is the generated English entry document. Edit tools/build-share-pages.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('pages/') && !p.startsWith('pages/src/') && p.endsWith('.html'),
    message:
      'Blocked: pages/*.html and pages/en/*.html are generated site pages. Edit pages/src/<id>.html (Russian) or pages/src/en/<id>.html (English), then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('dist/') || p.startsWith('dist-test/'),
    message:
      'Blocked: dist/ and dist-test/ are build output. Edit the source under app/src/ and run `npm run build` (dist/) or `npm run build:test` (dist-test/).'
  },
  {
    test: (p) => p === 'package-lock.json',
    message:
      'Blocked: package-lock.json is generated. Change package.json and run `npm install`.'
  },
  {
    test: (p) => p.startsWith('tests/app/snapshots/'),
    message:
      'Blocked: tests/app/snapshots/*.txt are structural goldens, regenerated by node tests/app/golden.js --update. Do not hand-edit one to make a run pass.'
  },
  {
    test: (p) => p === 'docs/decisions.md',
    message:
      'Blocked: docs/DECISIONS.md is the generated index of docs/decisions/. Add or edit a file there (template: .claude/templates/decision.template.md), then run node tools/decisions.js.'
  }
];

guard(() => {
  const input = readInput();
  const event = input.hook_event_name || 'PreToolUse';
  const filePath = input.tool_input && input.tool_input.file_path;
  const rel = relPath(filePath, input.cwd);
  if (rel === null) return undefined;
  const key = pathKey(rel);

  for (const rule of DENY) {
    if (rule.test(key)) return deny(event, rule.message);
  }

  if (key.startsWith(MIGRATIONS)) {
    const refs = remoteRefsHolding(rel.slice(MIGRATIONS.length));
    if (refs.length) {
      return deny(
        event,
        `Blocked: ${rel} is on ${refs.join(', ')}; CI applies every pushed migration to the test project and every migration on main to production, so it is history - write a new migration instead.`
      );
    }
  }
  return undefined;
});
