// PreToolUse(Edit|MultiEdit|Write|NotebookEdit): block direct writes to
// generated files and to a migration that a remote-tracking ref holds, after
// a bounded fetch - CI applies every pushed migration, so a pushed one is
// history. Git is the record; no file lists applied migrations. The
// reviewer writes only its report, issues/<id>/reviews/<name>.md (docs/decisions/,
// 2026-09-27) in the session's own checkout or in a linked worktree; a path
// in the main checkout from a worktree, or outside the repository, is denied. See
// .claude/README.md, "Hooks".

import path from 'node:path';
import {
  readInput,
  guard,
  deny,
  relPath,
  checkoutRoot,
  repoRoot,
  pathKey,
  remoteRefsHoldingMigration,
  migrationLockedMessage,
  MIGRATIONS_DIR as MIGRATIONS
} from './lib.mjs';

// Every test here runs against pathKey(rel), not rel itself: relPath() keeps
// real casing on POSIX, and a literal like 'data.json' must match regardless
// of how the caller happened to spell it - see pathKey()'s doc comment.
const DENY = [
  {
    test: (p) => p === 'data.json',
    message:
      'Blocked: data.json is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p === 'catalog.csv',
    message:
      'Blocked: catalog.csv is generated from data.js. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('i/'),
    message:
      'Blocked: i/*.html and i/en/*.html are generated share stubs. Edit data.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('en/'),
    message:
      'Blocked: en/index.html is the generated English entry document. Edit tools/build-share-pages.js, then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('pages/') && !p.startsWith('pages/src/') && p.endsWith('.html'),
    message:
      'Blocked: pages/*.html and pages/en/*.html are generated site pages. Edit pages/src/<id>.html (Russian) or pages/src/en/<id>.html (English), then run `node tools/build.js`.'
  },
  {
    test: (p) => p.startsWith('dist/') || p.startsWith('dist-test/'),
    message:
      'Blocked: dist/ and dist-test/ are build output. Edit the source under app/src/ and run `npm run build` (dist/) or `npm run build:test` (dist-test/).'
  },
  {
    test: (p) => p === 'package-lock.json',
    message:
      'Blocked: package-lock.json is generated. Change package.json and run `npm install`.'
  },
  {
    test: (p) => p.startsWith('tests/app/snapshots/'),
    message:
      'Blocked: tests/app/snapshots/*.txt are structural goldens, regenerated by node tests/app/golden.js --update. Do not hand-edit one to make a run pass.'
  },
  {
    test: (p) => p === 'docs/decisions.md',
    message:
      'Blocked: docs/DECISIONS.md is the generated index of docs/decisions/. Add or edit a file there (template: .claude/templates/decision.template.md), then run node tools/decisions.js.'
  }
];

const REVIEW_REPORT_RE = /^issues\/[a-z0-9][a-z0-9._-]*\/reviews\/[a-z0-9][a-z0-9._-]*\.md$/;
const REVIEW_TOOLS = new Set(['Write', 'Edit', 'MultiEdit']);
const REVIEWER_MESSAGE =
  'Blocked: the reviewer writes only its report, issues/<id>/reviews/<name>.md, with Write or Edit; everything else is read-only (docs/decisions/, 2026-09-27, "The reviewer writes its report to issues/<id>/reviews/ and nowhere else"). Return the fix to the orchestrator.';

guard(() => {
  const input = readInput();
  const event = input.hook_event_name || 'PreToolUse';
  const filePath = input.tool_input && input.tool_input.file_path;
  // Relative to the session's own checkout, so a worktree's report and its
  // generated files match; a path in another checkout is outside it.
  const sessionRel = relPath(filePath, input.cwd, checkoutRoot(input.cwd));
  // A reviewer dispatched from the main checkout keeps its cwd there while
  // the task lives in an agent-* worktree, so a report in a linked worktree
  // resolves against that worktree.
  const fileRoot = filePath
    ? checkoutRoot(path.resolve(input.cwd || '', filePath))
    : repoRoot();
  const reportRel =
    fileRoot !== repoRoot() ? relPath(filePath, input.cwd, fileRoot) : sessionRel;
  if (
    input.agent_type === 'reviewer' &&
    !(
      reportRel !== null &&
      REVIEW_TOOLS.has(input.tool_name) &&
      REVIEW_REPORT_RE.test(pathKey(reportRel))
    )
  ) {
    return deny(event, REVIEWER_MESSAGE);
  }
  // A worktree session still may not write the main checkout's generated files.
  const rel = sessionRel !== null ? sessionRel : relPath(filePath, input.cwd);
  if (rel === null) return undefined;
  const key = pathKey(rel);

  for (const rule of DENY) {
    if (rule.test(key)) return deny(event, rule.message);
  }

  if (key.startsWith(MIGRATIONS)) {
    const refs = remoteRefsHoldingMigration(rel.slice(MIGRATIONS.length), { fetch: true });
    if (refs.length) return deny(event, migrationLockedMessage(rel, refs));
  }
  return undefined;
});
