import {
  copyFileSync,
  createReadStream,
  existsSync,
  readFileSync,
  statSync,
  symlinkSync
} from 'node:fs';
import { extname, join, normalize, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';
import { defineConfig, type Plugin } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';

const ROOT = fileURLToPath(new URL('.', import.meta.url));

/* What the build adds to `dist/` from the repository root, beside the bundle:
   the linked folders, and the files the `<noscript>` fallback links. */
const ROOT_DIRS = ['img', 'og', 'card', 'pages'];
const NOSCRIPT_FILES = ['catalog.csv', 'data.json', 'llms.txt'];

/*
 * The artwork, beside the page that asks for it.
 *
 * The build emits the application; the pictures are made outside it and live in
 * the repository root. Without this the built page opens and immediately fails
 * five requests for `img/*.webp` - which nothing noticed while the opening
 * screen happened to be one the rewrite had not reached, and which CI caught
 * the moment Core rules started drawing four cards on it.
 *
 * Linked rather than copied: 80 MB on every build is not a cost worth paying
 * for a folder that has not changed. `junction` is what makes that work on
 * Windows without elevation, and is ignored on everything else.
 *
 * The generated site pages (`pages/`) ride the same junction: they are written
 * before `vite build`, because `npm run build` runs `npm run data` first.
 */
function artwork(out: string): Plugin {
  return {
    name: 'dhloot-artwork',
    apply: 'build',
    closeBundle() {
      for (const dir of ROOT_DIRS) {
        const at = join(ROOT, out, dir);
        if (!existsSync(at)) symlinkSync(join(ROOT, dir), at, 'junction');
      }
    }
  };
}

/* The <noscript> fallback's own three links: `catalog.csv`,
 * `data.json` and `llms.txt` are generated files at the repository root, not
 * inputs Vite's own graph ever touches, so nothing put them in `dist/` once
 * the build stopped being "copy the root folder as-is". Files, not the
 * `artwork()` junction above - these are small and regenerated by
 * `node tools/build.js`, not an 80 MB tree not worth re-copying on every
 * build. `tools/smoke-http.mjs` asserts every `noscript a[href]`
 * resolves under `dist/`, and was proven to fail before this copy existed.
 */
function noscriptData(out: string): Plugin {
  return {
    name: 'dhloot-noscript-data',
    apply: 'build',
    closeBundle() {
      for (const file of NOSCRIPT_FILES) {
        copyFileSync(join(ROOT, file), join(ROOT, out, file));
      }
    }
  };
}

/* The data beside the bundle: `data.js` stays a classic script that assigns
   `window.LOOT`, cached apart from the hashed modules and read without an
   async bootstrap. docs/specs/CONTRACTS.md section 4. */
function dataScript(): Plugin {
  return {
    name: 'dhloot-data-script',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'data.js',
        source: readFileSync(new URL('./data.js', import.meta.url), 'utf8')
      });
    }
  };
}

/* The same root files for `npm run dev`. The dev server resolves every URL
   under `app/`, where none of these exist, so without this `data.js` is a 404
   and the page draws nothing. `build` never runs it. */
const TYPES: Record<string, string> = {
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.csv': 'text/csv; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.webp': 'image/webp',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml'
};

function rootFiles(): Plugin {
  const files = new Set(['data.js', ...NOSCRIPT_FILES]);
  return {
    name: 'dhloot-root-files',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        let rel: string;
        try {
          rel = normalize(decodeURIComponent(req.url?.split(/[?#]/)[0] ?? '')).replace(
            /^[/\\]+/,
            ''
          );
        } catch {
          next();
          return;
        }
        const file = join(ROOT, rel);
        const listed = files.has(rel) || ROOT_DIRS.includes(rel.split(sep)[0] ?? '');
        if (!listed || !existsSync(file) || !statSync(file).isFile()) {
          next();
          return;
        }
        res.setHeader('Content-Type', TYPES[extname(file)] ?? 'application/octet-stream');
        createReadStream(file).pipe(res);
      });
    }
  };
}

/* `app/` is the only application root; the build writes `dist/`, which
   `ci.yml`'s `deploy` job publishes. `vite build --mode test` writes
   `dist-test/` instead, the build `tests/app/` drives, with the fake cloud
   switched on (docs/specs/COVERAGE.md, "Test layers"). Vitest's own default
   mode is also `test`, so the switch needs `command === 'build'` as well, or
   `npm run test` would flip the outDir and the define. */
export default defineConfig(({ command, mode }) => {
  const testBuild = command === 'build' && mode === 'test';
  const OUT = testBuild ? 'dist-test' : 'dist';
  /* Sign-in is configured by two values; the test build and vitest have
     none. `vite build` reads only the process environment (the `deploy` job
     sets both), never `app/.env.local`, so a local `npm run build` - and
     `check:built` - stays the unconfigured build unless they are on the
     command line. The dev server reads `app/.env.local`. */
  const cloudEnv: Record<string, string | undefined> =
    testBuild || process.env['VITEST']
      ? {}
      : command === 'build'
        ? process.env
        : loadEnv(mode, join(ROOT, 'app'), 'VITE_');
  return {
    root: 'app',
    /* The manifest, the service worker and the icons, copied verbatim: the
       worker must not pass through the bundle (docs/specs/META.md section 9). */
    publicDir: 'public',
    /* A relative base, not '/daggerheart-loot/': the same build serves from
       Pages, `vite preview` and the test server at any path. */
    base: './',
    plugins: [svelte(), dataScript(), artwork(OUT), noscriptData(OUT), rootFiles()],
    /* JSON literals, so a branch of main.ts a build does not take - the
       fake's in `dist/`, the Supabase client's in an unconfigured build -
       is dead code, and its chunk is never emitted. */
    define: {
      'import.meta.env.VITE_CLOUD_FAKE': JSON.stringify(testBuild),
      'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(cloudEnv['VITE_SUPABASE_URL'] ?? ''),
      'import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY': JSON.stringify(
        cloudEnv['VITE_SUPABASE_PUBLISHABLE_KEY'] ?? ''
      )
    },
    /* Under vitest the modules are loaded the way a server would, and Svelte then
       hands back its server build - where `mount` does not exist. Asking for the
       browser condition during tests is what makes a component test a component
       test rather than a render-to-string. */
    resolve: process.env['VITEST'] ? { conditions: ['browser'] } : {},
    build: {
      outDir: '../' + OUT,
      emptyOutDir: true,
      sourcemap: false
    },
    test: {
      environment: 'jsdom',
      /* Vitest defaults to 5000ms, which is below what these tests actually do:
         axe over a full page in jsdom takes seconds, and the slowest a11y specs
         were measured at 13.5s. The default held only on an idle machine - one
         `npm run check` with a single puppeteer probe alongside produced 92
         failures, 71 of them `Test timed out in 5000ms`, on a suite that passes
         658/658 at 30s.

         30s is a little over twice the slowest measured test, so a genuinely
         hung test still fails rather than hanging the run. Scoping it to the
         a11y specs alone was considered and dropped: vitest has no per-file
         timeout without splitting into projects, and 30s is a bounded cost for
         a non-a11y test to hang before failing, not an unbounded one.

         The second half of the problem - a timed-out test leaves `axe.run()`
         in flight and axe holds a global lock, so one timeout takes the rest of
         the file with it (`Axe is already running`) - was not a timeout value
         and lives in app/src/test/a11y.ts instead: expectNoA11yViolations
         clears axe's `_running` flag before every run, so an abandoned run from
         a timed-out neighbour can no longer block the next one. See
         app/src/test/a11y.test.ts for the regression test. */
      testTimeout: 30_000,
      include: ['src/**/*.test.ts'],
      setupFiles: ['./vitest-setup.ts'],
      coverage: {
        provider: 'v8',
        /* Everything that ships, not only the parts that are easy to measure.
           Leaving components out was how a number in the eighties described two
           directories out of four. */
        include: ['src/**/*.ts', 'src/**/*.svelte'],
        exclude: [
          'src/**/*.test.ts',
          /* Test-only helpers, and the one file that is types and nothing else
             - it emits no code, so a percentage of it is noise. */
          'src/test/**',
          'src/ports/types.ts',
          /* `pngOf`'s canvas conversion cannot run in jsdom at all - no Image,
             no canvas, no toBlob - so a percentage of this file would measure
             one test double and nothing else. It is exercised for real by
             tests/app/states.js's copy-image case, which drives the built app
             in Chrome and reads a real assertion on whichever of the two
             outcomes this build actually produces - a real picture (the
             same-origin build over HTTP), or the record's text and its own
             toast (a tainted canvas) - rather than only proving the promise
             does not hang. The caller's own branching on a rejection
             (RecordActions.svelte's copyImage) is covered here, through
             fakeImage. `download` is different: it touches only
             `URL.createObjectURL`/`revokeObjectURL` and a plain `<a>`,
             all of which jsdom has, so `ports.test.ts` covers it directly
             rather than through `states.js` (which never reaches it either -
             that suite's stubbed clipboard accepts the picture, so `download`
             is never called). The whole file still carries
             one exclusion rather than an inline ignore on `pngOf` alone,
             because `pngOf` is most of it. */
          'src/ports/image.ts',
          'src/vite-env.d.ts',
          /* The entry point that mounts the app onto a real DOM - exercised for
             real by tools/smoke-http.mjs, which opens the built page over
             HTTP. */
          'src/main.ts'
        ],
        reporter: ['text', 'text-summary'],
        /* Per directory, because one global number lets a well covered library
           pay for a component nobody tested. The bars differ because the
           obligations differ: lib is pure and has no excuse, ports wrap browser
           APIs whose happy paths jsdom cannot reach, everything else is drawn on
           screen and is checked through behaviour. `perFile` is the part that
           matters - it is what makes a file with no test at all fail, without
           demanding a test file per source file. */
        thresholds: {
          perFile: true,
          'src/lib/**': { lines: 95, functions: 95, branches: 85, statements: 90 },
          'src/ports/**': { lines: 70, functions: 80, branches: 55, statements: 70 },
          /* Every component except the ones named below. A threshold glob does
             not override a wider one - both are applied - so the exception has to
             be carved out of the pattern rather than layered on top of it. */
          'src/**/!(Button|DiceBar|Badge).svelte': {
            lines: 85,
            functions: 80,
            branches: 75,
            statements: 85
          },
          /* Three components carry their own exception, a file rather than a
             rule - each named here rather than lowering the bar for every
             component to suit one (see CLAUDE.md). */
          /* Five buttons built from three props and nothing else: every branch
           Svelte generates for it is an attribute update path, and even a test
           that switches the language cannot reach them all. */
          'src/components/DiceBar.svelte': {
            lines: 85,
            functions: 80,
            branches: 55,
            statements: 85
          },
          /* Svelte compiles every attribute into an update path; Button is
             small enough that its own tests - seven of them, including one
             that changes its props under it - still cannot reach them all. */
          'src/components/Button.svelte': {
            lines: 85,
            functions: 80,
            branches: 60,
            statements: 85
          },
          /* One attribute (`title`) and one class interpolation (`cls`): the
             whole component is a single optional-attribute update path,
             present-vs-absent, plus a class-value update path - badge.test.ts
             covers both directions of each, including a rerender that swaps
             both, and 50% branch is still the ceiling. */
          'src/components/Badge.svelte': {
            lines: 85,
            functions: 80,
            branches: 50,
            statements: 85
          },
          'src/state/**': { lines: 95, functions: 95, branches: 85, statements: 90 }
        }
      }
    }
  };
});
