/* The interface dictionary.
 *
 * docs/specs/I18N.md keeps this separate from record text on purpose: this is
 * small, typed and reviewed, while record text is 1272 pairs maintained with
 * the data. Only interface strings belong here.
 *
 * Parity is a compile error rather than a test. `Dict` is derived from the
 * Russian side, so an English side missing a key does not typecheck and a key
 * only English has does not either. The old build could only find that out by
 * parsing its own source at test time.
 *
 * This grows with the rewrite. A key is added when a component needs it, not in
 * advance - an unused string is a translation somebody maintains for nothing,
 * and the old dictionary accumulated five of those. */

import { legacyDateText } from './legacy.js';
import type { Lang, Section } from './types.js';

const ru = {
  /* The chrome that has no text of its own, and so has no other place to be
     named. Without these the tab bar and the language group are unlabelled to
     a screen reader. */
  docTitle: 'Генератор лута — Daggerheart',
  skipToContent: 'К содержимому',
  sectionsLabel: 'Разделы',
  langLabel: 'Язык',
  close: 'Закрыть',

  /* The ten sections, in tab order */
  std: 'Обычные правила',
  alt: 'Альт. таблицы',
  wondrous: 'Wondrous',
  dread: 'Dread',
  voa: 'Vault of Ages',
  dv: "Dragon's Vault",
  community: 'Сообщества',
  tables: 'Таблицы',
  lists: 'Списки',
  search: 'Поиск',

  /* Outside the app a bare name loses the badge, so a consumable says so */
  item: 'Предмет',
  cons: 'Расходник',
  craftInto: 'Улучшается до',
  craftFrom: 'Получается из',
  /* The set line on a card: names the set, not a count, so one word covers
     any number of members (`docs/DECISIONS.md`, "Set membership"). */
  setLabel: 'Комплект',

  /* The record card's actions, and what each one says when it is done */
  copyName: 'Скопировать название',
  copyText: 'Скопировать текст',
  copyImg: 'Скопировать изображение',
  sImg: 'Картинка',
  sText: 'Текст',
  openPage: 'Страница',
  showInTable: 'показать в таблице',
  rollNo: 'номер',

  /* The book a record comes from, as the badge and the metadata line name it */
  srcCore: 'Core',
  srcHnf: 'Hope & Fear',
  srcWond: 'Wondrous',
  srcDread: 'Dread',
  srcVoa: 'Vault of Ages',
  srcDv: "Dragon's Vault",
  /* Matches `frameF`/`subFrames` below - one word for the concept in
     Russian, verified against ru.daggerheart.su/frame ("Сеттинги" is both
     that page's own title and its term for one entry on it). */
  srcFrame: 'Сеттинг',
  srcComm: 'Сообщества',
  copyLink: 'Скопировать ссылку',
  sendAll: 'Отправить',
  nameCopied: 'Название скопировано',
  imgCopied: 'Картинка скопирована',
  textCopied: 'Текст скопирован',
  linkCopied: 'Ссылка скопирована',
  copyFailed: 'Не удалось скопировать',
  /* The copy-all-options button gets its own toast. */
  rollCopied: 'Варианты скопированы',
  /* A cross-origin picture taints the
   *  canvas it is redrawn on, so the picture can never leave it - falls back
   *  to the record's text instead of reporting a false success. Distinct
   *  from a clipboard that simply refuses the picture, which offers a
   *  download instead (`imgSaved`/`imgFailed`), and from `copyFailed`, the
   *  generic every-other-copy-button wording. */
  imgTainted: 'Не удалось скопировать картинку - скопирован текст',
  imgSaved: 'Картинка сохранена',
  imgFailed: 'Не удалось сохранить картинку',

  /* Rolling */
  roll: 'Бросить',
  randomIn: 'Случайно',
  rollResult: 'Результат броска',
  stepDown: 'На единицу меньше',
  stepUp: 'На единицу больше',

  /* The licence notice, in three parts so the link is an element rather than
     markup in a string. The verbatim citation lives entirely in the first
     part - tests/derived.js pins it in app.js, and it must read the same here. */
  footBefore:
    "Данные: Daggerheart Core Set, Hope & Fear, Wondrous Loot, Dread GM Toolbox, Vault of Ages, The Dragon's Vault, Community Magic Items, Alternate Loot & Consumable Tables. Перевод: daggerheart.su и собственные материалы. Daggerheart © Darrington Press. This product includes materials from the Daggerheart System Reference Document 2.0, © Critical Role, LLC. under the terms of the Darrington Press Community Gaming (DPCGL) License. More information can be found at ",
  footLink: 'daggerheart.com',
  footAfter: '. There are no previous modifications by others.',
  /* The folded notice's one visible line; the full text above sits under it. */
  footSummary: 'Daggerheart © Darrington Press - DPCGL - Источники и лицензия',
  /* The footer's nav row: the site's static pages (pages/<id>.html). */
  footNavLabel: 'Страницы сайта',
  installLink: 'Установить как приложение',
  privacyLink: 'Конфиденциальность',
  termsLink: 'Условия использования',

  /* The heading of each section, and the line under it. The heading is not
     always the tab's word: the tab says "Сообщества" and the page says
     "Предметы сообществ", because on the page it is the things that matter. */
  pageWondrous: 'Wondrous Loot',
  pageDread: 'Dread GM Toolbox',
  pageVoa: 'Vault of Ages',
  pageDv: "The Dragon's Vault",
  pageCommunity: 'Предметы сообществ',
  pageStd: 'Обычные правила',
  subStd: 'Бросок по таблицам корника и дополнения Hope & Fear.',
  /* The five dice buttons say which rarity band they cover */
  common: 'Обычная',
  uncommon: 'Необычная',
  rare: 'Редкая',
  veryRare: 'Очень редкая',
  legendary: 'Легендарная',
  source: 'Источник',
  keepOneSource: 'Нужен хотя бы один источник',
  filter: 'Тип',
  fItems: 'Предметы',
  fCons: 'Расходники',
  fEquip: 'Снаряжение',
  keepOneKind: 'Нужен хотя бы один тип',
  or: 'ИЛИ',
  copyRoll: 'Скопировать все варианты',
  subWondrous: 'Введите результат броска или получите случайную позицию.',
  subVoa: 'Выберите раздел книги и бросьте кость по нему.',
  subCommunity: 'Выберите происхождение и бросьте d10.',

  /* The alternate tables. Two dice with names instead of a sum, so each one
     is labelled and the card says which of them found it. */
  pageAlt: 'Альтернативные таблицы',
  subAlt: 'Бросок Костей Дуальности по объединённым таблицам обеих книг.',
  rarity: 'Редкость',
  hopeDie: 'Кость Надежды',
  fearDie: 'Кость Страха',
  rollDuality: 'Бросить кости',
  hope: 'Надежда',
  fear: 'Страх',
  crit: 'Критический успех!',
  critSub:
    'Игрок берёт любую позицию из таблицы этой редкости. Мастер может разрешить подняться на ступень выше.',
  /* One link per kind that is on; with a single kind there is nothing to tell
     apart and the label stays general. */
  openTable: 'Открыть таблицу',
  openItems: 'Таблица предметов',
  openCons: 'Таблица расходников',
  /* The whole phrase rather than "Поднять до" plus a rarity: Russian needs the
     genitive there, which no concatenation of the chip labels can produce.
     There is no `common` twin - a critical success only ever steps up. */
  bumpUncommon: 'Поднять до Необычной',
  bumpRare: 'Поднять до Редкой',
  bumpVeryRare: 'Поднять до Очень редкой',
  bumpLegendary: 'Поднять до Легендарной',

  voaSection: 'Раздел книги',
  voaArtifact: 'Артефакты',
  voaCursed: 'Проклятые предметы',
  /* Singular, for the badge on one card: it is a thing, not a shelf. */
  voaArtifact1: 'Артефакт',
  voaCursed1: 'Проклятый предмет',
  unique: 'Уникальное',
  uniqueHint: 'В книге стоит одним рангом — лестницы улучшений у этой вещи нет',
  homeHint: 'Открывать этот раздел при запуске',
  /* The same button once it is on: the live app renames it rather than only
     filling it in, so a screen reader hears the state and not just the offer. */
  homeOn: 'Открывается при запуске',
  helpHint: 'Как это работает',
  fieldHelp: 'Подсказка: %s',
  rollLabelFor: 'Результат броска',
  /* Singular, and not the tab's word: the tab says "Сообщества" because it
     names a section, the label above the picker asks for one community. */
  communityLabel: 'Сообщество',

  notFound: 'Предмет не найден',
  notFoundSub: 'Возможно, ссылка устарела или данные были изменены.',
  noData: 'Данные не загрузились. Обновите страницу.',
  /* The smallest error boundary: a page that throws mid-render draws
     this instead of leaving a blank middle under a working tab bar. */
  pageError: 'Что-то пошло не так на этой странице.',
  reloadPage: 'Обновить страницу',

  /* The stat line needs three words the vocabulary maps do not carry */
  tier: 'Ранг',
  eqTh: 'Пороги',
  eqScore: 'Броня',
  /* The equipment tables' own facet row labels */
  eqClass: 'Класс',
  eqTrait: 'Характеристика',
  eqRange: 'Дистанция',
  eqBurden: 'Хват',
  eqLineF: 'Линейка',

  /* The print card's own stat-strip labels: shorter than the interface's,
     because 63mm has no room for "Характеристика" - the layout says "Черта". */
  pcDmg: 'Урон',
  pcTrait: 'Черта',
  pcRange: 'Дистанция',
  pcArmor: 'Броня',
  thLight: 'Лёгкий урон',
  thMajor: 'Ощутимый урон',
  thSevere: 'Тяжёлый урон',

  /* The two groups the tab bar has no word for - both a slice through every
     book rather than a book of their own. */
  grpEquipment: 'Снаряжение',
  grpOther: 'Прочее',
  subStarting: 'Стартовые',
  subFrames: 'Сеттинги',
  /* The three equipment tables' sub-caption, shorter than the book's own name
     for the kind of gear - "Основное оружие" on the badge, "Оружие" here. */
  subWeapon: 'Оружие',
  subSecondary: 'Вторичное',
  subArmor: 'Броня',

  subTables:
    'Все таблицы целиком, включая оружие и броню, - можно листать, фильтровать и открывать карточки.',
  subLists: 'Соберите добычу в список и отправьте игрокам одной ссылкой.',
  /* "по всем N позициям" needs "всем" to agree with the numeral, so the
     sentence leaves it out and reads for any count. */
  subSearch:
    'Поиск сразу по 1272 позициям - добыча, расходники и снаряжение, на русском и на английском.',
  subSearchOwn: 'И %n ваш предмет.|И %n ваших предмета.|И %n ваших предметов.',

  searchPh: 'Поиск по названию или описанию…',
  tableLink: 'Ссылка на таблицу',
  tableLinkCopied: 'Ссылка на таблицу скопирована',
  view: 'Вид',
  viewList: 'Списком',
  viewGrid: 'Сеткой',
  nothing: 'Ничего не найдено',
  startTyping:
    'Начните вводить запрос. Несколько слов ищутся в любом порядке, «фраза в кавычках» - дословно.',
  selectAll: 'Выбрать все',
  selected: 'Выбрано',
  /* A `|` string is a form set for `plural()` (I18N.md, "Rules"). */
  selectedN: 'Выбрана %n позиция|Выбрано %n позиции|Выбрано %n позиций',
  itemsN: '%n позиция|%n позиции|%n позиций',
  listsN: '%n список|%n списка|%n списков',
  /* `%s` is a counted plural, `%m` the account's limit. */
  ofLimit: '%s из %m',
  clearSel: 'Снять выделение',
  selRegion: 'Выбранные записи',
  copySel: 'Скопировать',
  selCopied: 'Выбранное скопировано',

  /* The table filter: the strip, the panel it folds open, and the link that
     hands the picked state to somebody else. */
  filters: 'Фильтры',
  kindF: 'Тип',
  frameF: 'Сеттинг',
  commF: 'Сообщество',
  anyValue: 'любое',
  outOf: 'из',
  dropValue: 'Убрать из фильтра',
  resetAll: 'Сбросить всё',
  filterLink: 'Ссылка на фильтры',
  filterLinkCopied: 'Ссылка на фильтры скопирована',

  /* A section heading's own link, off `sectionHead` in app.js - the table
     link button's sibling, one level down. */
  copySection: 'Скопировать ссылку на этот раздел',
  sectionLinkCopied: 'Ссылка на раздел скопирована',

  /* The add-to-list row every full card draws, and the toast it and the pin
     button both raise - app.js 109-164, 199-200. */
  addToList: 'Добавить в список',
  addTo: 'Добавить в',
  inLists: 'Лежит в списках',
  newList: 'Новый список',
  listNamePh: 'Например: клад дракона',
  create: 'Создать',
  cancel: 'Отмена',
  findList: 'Найти список',
  showMore: 'Показать ещё',
  addedTo: 'Добавлено в «%s»',
  removedFrom: 'Убрано из «%s»',
  nameFirst: 'Сначала назовите список',
  untitled: 'Без названия',
  saveFailed:
    'Не удалось сохранить: браузер не дал записать в локальное хранилище — оно заблокировано или переполнено',
  /* The shared page - app.js 3130-3170: a list from another player, the
     bad-link page's own link home, and the button that saves the shared
     list as a new own list. */
  sharedList: 'Список от другого игрока',
  saveShared: 'Сохранить себе',
  toStart: 'На главную',
  print: 'Печать',
  printHint: 'Собрать карточки для печати: девять на лист A4',
  printColor: 'Цветная',
  printBW: 'Чёрно-белая',
  printStd: 'Обычная',
  printCompact: 'Компактная',
  printSize: 'Размер карты',
  printNow: 'Отправить на печать',
  printLink: 'Ссылка на набор',
  printTitle: 'Печать карточек',
  printSub: 'Карточек: %n. Листов A4: %p. Размер карты 63×88 мм — как у обычной игральной.',
  printSubCompact: 'Карточек: %n. Листов A4: %p. Размер карты 44×63 мм — шестнадцать на лист.',
  printNote:
    'В окне печати выберите A4, книжную ориентацию и поля «нет». Лист светлый нарочно: так он читается и на чёрно-белом принтере, и не съедает картридж.',
  printEmpty: 'Печатать нечего: в адресе не нашлось ни одной вещи.',
  back: 'Назад',
  printTooMany:
    'Карточек за один раз: не больше %n. Не попали на лист: %d. Разделите набор на части.',
  homeSet: 'Приложение будет открываться на этом разделе',
  homeReset: 'Приложение снова будет открываться на обычных правилах',

  /* The lists index - app.js 107-108/110-111/154/156/159-160/162-168/163/148,
     and the storage notice's two live forms. */
  dismiss: 'Скрыть',
  readMore: 'подробнее',
  listCreated: 'Список «%s» создан',
  noLists: 'Списков пока нет - создайте первый выше.',
  share: 'Поделиться',
  del: 'Удалить',
  listEmpty: 'Список пуст',
  noStorageTitle: 'Браузер блокирует локальное хранилище.',
  noStorage:
    'Списки не сохранятся после перезагрузки страницы. Обычно так бывает в режиме инкогнито или при запрете сайту хранить данные. Ссылкой поделиться всё равно можно.',
  badStorageTitle: 'Сохранённые списки не удалось прочитать.',
  badStorage:
    'Похоже, их записала другая версия приложения, расширение браузера или другая вкладка на этом сайте. Исходное содержимое сохранено под отдельным ключом и не потеряно; дальнейшие изменения будут сохраняться заново, начиная с чистого списка.',
  localOnlyTitle: 'Списки живут только в этом браузере.',
  localOnly:
    'Очистка данных сайта, режим инкогнито или другое устройство — и списки пропадут. Чтобы не потерять, нажмите «Ссылка себе»: весь состав закодирован прямо в адресе, и список восстанавливается из неё целиком, вместе с обеими заметками. Эта ссылка только для вас — в ней есть и то, что вы писали в «Только для мастера». Игрокам отправляйте «Ссылка игрокам» или результат кнопки «Скопировать текст»: туда попадает лишь то, что написано в «Для игроков». В адресной строке браузера тоже лежит ссылка для игроков, так что скопировать её оттуда безопасно. Только помните, что ссылка — это снимок: она помнит список таким, каким он был в момент копирования. Добавили позицию или поправили заметку — сохраните ссылку заново.',
  deleteConfirm: 'Удалить список «%s»? Отменить удаление нельзя.',
  /* Delete gets an undo, like every other destructive action. */
  listDeleted: 'Список «%s» удалён',
  playersLinkCopied: 'Ссылка для игроков скопирована — заметок мастера в ней нет',
  badShare: 'Ссылка повреждена или собрана в другой версии данных.',
  /* An old link naming a renumbered or deleted record would otherwise lose
     those entries with no sign anything was missing - toasted once, on the
     shared page and after restoring a copy. One colon form: a pronoun after
     "Пропущена 21 позиция" would refer to 21 records as to one. */
  droppedItems: 'Пропущено позиций, которых больше нет в данных: %n',

  /* The list page - app.js 114-195, the address, the actions, the notes,
     the roll panel and a row's own controls. */
  rename: 'Название списка',
  sharePlayers: 'Ссылка игрокам',
  shareGm: 'Ссылка себе',
  gmLinkCopied: 'Ссылка со всеми заметками скопирована — она только для вас',
  listCopied: 'Список скопирован',
  listEmptyHint:
    'Пока пусто. Откройте «Таблицы» или «Поиск», отметьте нужное галочками и нажмите «Добавить в список» - или сделайте это прямо с карточки предмета.',
  listNotFound: 'Список не найден',
  listNotFoundSub: 'Возможно, он удалён или открыт в другом браузере.',
  rollBy: 'Бросок по списку',
  rollHint: 'Бросьте кубик и введите результат - или нажмите кнопку',
  clear: 'Сбросить',
  note: 'Заметка',
  listNote: 'Заметки',
  noteHead: 'Заметка',
  notePub: 'Для игроков',
  noteHid: 'Только для мастера',
  notePubHint: 'уедет с текстом и ссылкой для игроков',
  noteHidHint: 'останется у вас',
  listNotePhPub: 'Например: лавка закрыта до утра',
  listNotePhHid: 'Например: позиции 9-10 лежат под прилавком',
  notePhPub: 'Как предмет выглядит, что о нём знают',
  notePhHid: 'Хоумбрю, подвох, что знает только мастер',
  noteClear: 'Очистить заметку',
  noteCleared: 'Заметка очищена',
  qty: 'Кол-во',
  gold: 'Золото',
  position: 'Позиция в списке',
  dragHint: 'Перетащите, чтобы изменить порядок',
  removeItem: 'Убрать из списка',
  removedItem: 'Убрано из списка: «%s»',
  movedItem: '«%s» - позиция %n из %m',
  undo: 'Вернуть',
  pickAll: 'Выбрать все',
  /* A selection's total and taken pieces - a colon form or an invariant
     abbreviation, so no count has to agree with a word (I18N.md, "Rules"). */
  total: 'Итого',
  unpricedN: 'без цены: %n',
  pickQty: 'Взять',
  pickQtyOf: 'Взять: %s',
  pickOf: 'из %n',
  /* The ends of the take count; each name starts with the word on the button. */
  pickMin: 'Мин',
  pickMax: 'Макс',
  pickMinOf: 'Мин, взять 1: %s',
  pickMaxOf: 'Макс, взять все: %s',
  pcsN: '%n шт.',
  eachPrice: 'по %s',
  moneyAs: 'Отображение цен',
  money_bag: 'Как в книге',
  money_coin: 'Монетами',
  goldUnit: 'зол.',
  batchMoney: 'Цены',
  batchNoPrice: 'Убрать цену',
  repricePct: 'Изменить на, %',
  repriceDown: 'Сделать скидку',
  repriceUp: 'Поднять цену',
  repriceHint: 'Минус - скидка, плюс - наценка. Считается от текущей цены.',
  repriceDone: 'Цены пересчитаны',
  repriceUndo: 'Вернуть',
  batchDeleted: 'Убрано из списка',
  guessApply: 'Проставить эти цены',
  guessWhy:
    'В книге цен нет: Core (с. 105) оставляет их мастеру. Порядок величин взят из общей таблицы сообщества - у снаряжения по рангу, у добычи по редкости. Это не канон, а точка отсчёта; выбранным строкам цены будут перезаписаны.',
  guessNoTier: 'нечем оценить',
  guessNoRarity: 'редкость не указана',
  guessDone: 'Цены проставлены',

  /* The account: the header control and `#/account`. Texts name what an
     account is for in general terms, true in every release (I18N.md,
     "Rules"). `%s` is a provider name, Google or Discord, never translated. */
  account: 'Аккаунт',
  signIn: 'Войти',
  accountSub: 'Отображение, способы входа, выход и ваши данные.',
  menuLabel: 'Меню аккаунта',
  menuLists: 'Мои списки',
  displayHead: 'Отображение',
  displayLead:
    'Эти настройки действуют на всех ваших устройствах. Вид таблиц и печать, выбранные на их страницах, сохраняются только до перезагрузки.',
  keepBefore: 'Только до перезагрузки. Чтобы сохранить, измените в ',
  keepLink: 'настройках аккаунта',
  keepAfter: '.',
  displayHome: 'Раздел при запуске',
  printCompactBox: 'Компактный лист',
  displayNotify: 'Добавление из чужого списка',
  notifyAsk: 'Спрашивать',
  notifyAlways: 'Сообщать владельцу',
  notifyNever: 'Не сообщать',
  notifyHint:
    'Когда вы добавляете предметы из чужого списка в свой, сообщить об этом его владельцу?',
  signInLead:
    'Войдите, чтобы ваши данные были доступны на всех устройствах. Всё остальное работает и без входа.',
  signInWith: 'Войти через %s',
  consentBefore: 'Входя, вы принимаете ',
  consentTerms: 'условия',
  consentMid: ' и ',
  consentPrivacy: 'политику конфиденциальности',
  consentAfter: '.',
  signedInAs: 'Вы вошли как',
  via: 'через %s',
  providers: 'Способы входа',
  notConnected: 'не подключён',
  connect: 'Подключить %s',
  redirecting: 'Переходим в %s...',
  disconnect: 'Отключить',
  onlyMethod:
    '%s - единственный способ входа, поэтому его нельзя отключить. Подключите второй, чтобы отключить этот.',
  alreadyLinked: 'Этот аккаунт %s уже подключён к другому пользователю.',
  signOutHead: 'Выход',
  signOut: 'Выйти',
  signOutAll: 'Выйти на всех устройствах',
  signOutAllHint:
    '«Выйти на всех устройствах» завершает вход и на других телефонах и компьютерах.',
  deleteHead: 'Удаление аккаунта',
  deleteHint: 'Аккаунт и все связанные с ним данные будут удалены навсегда.',
  deleteOpen: 'Удалить аккаунт...',
  deleteTypeWord: 'Чтобы подтвердить, введите слово',
  deleteWord: 'удалить',
  deleteFinal: 'Удалить навсегда',
  signedOut: 'Вы вышли из аккаунта.',
  accountDeleted: 'Аккаунт удалён.',
  accountFailed: 'Не получилось. Проверьте соединение и попробуйте ещё раз.',
  /* The account's data export (docs/specs/FEATURES.md, "Account"). */
  yourData: 'Ваши данные',
  yourDataHint:
    'Всё, что хранится в аккаунте, одним архивом ZIP: файл lists.json со списками и, если есть свои предметы, homebrew.json с ними, их источниками и картами. Чтобы перенести всё в другой аккаунт, импортируйте архив сначала на странице «Мои предметы», затем на странице «Мои списки»: за один раз - до 1000 списков и до 1000 своих предметов.',
  exportData: 'Скачать мои данные (ZIP)',

  /* Account lists: the index groups, the save status, the sign-in prompts,
     the delete confirm and the limits (docs/specs/FEATURES.md, "Lists"). */
  groupAccount: 'Ваш аккаунт',
  groupBrowser: 'Этот браузер',
  noCloudLists: 'В аккаунте пока нет списков - создайте первый выше.',
  cloudLoading: 'Загружаем...',
  cloudLoadFailed: 'Не получилось загрузить списки аккаунта.',
  retry: 'Повторить',
  editedAgo: 'изменён %s',
  editedNow: 'изменён только что',
  saving: 'Сохраняем...',
  savedState: 'Сохранено',
  notSaved: 'Не сохранено',
  signInToCreate:
    'Войдите, чтобы создавать списки: они хранятся в аккаунте и открываются на любом устройстве.',
  signInToCreateShort: 'Войдите, чтобы создать список.',
  signInToSave: 'Войдите, и список сохранится в ваш аккаунт.',
  signInToOpen: 'Если это список из вашего аккаунта, войдите, чтобы открыть его.',
  deleteCloudConfirm:
    'Удалить список «%s»? Ссылки для игроков и мастера перестанут работать. Отменить удаление нельзя.',
  limitLists:
    'Достигнут предел списков в аккаунте: %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  limitEntries:
    'Достигнут предел позиций в списке: %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  limitSnapshots:
    'Достигнут предел копий предметов других игроков в списке: %n КБ. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  limitOther: 'Достигнут предел: %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  writeRefused: 'Изменение не сохранилось: сервер его не принял. Показан список из аккаунта.',

  /* Homebrew: the author's own items, sources and sections, the editor and its
     failure states (docs/specs/FEATURES.md, "Homebrew"). "(HB)" is Latin in both
     languages. */
  myItems: 'Мои предметы',
  subHomebrew:
    'Предметы, которых нет в книгах: они ищутся вместе с каталогом, попадают в таблицы и добавляются в списки.',
  srcHomebrew: 'Хоумбрю',
  hbTag: '%s (HB)',
  hbMark: 'HB',
  relLess: 'свернуть',
  hbSources: 'Источники',
  hbItemsN: '%n предмет|%n предмета|%n предметов',
  hbSectionsN: '%n раздел|%n раздела|%n разделов',
  hbSectionsBtn: 'Разделы',
  hbRename: 'Переименовать',
  hbNewSource: 'Новый источник',
  hbNewSection: 'Новый раздел',
  hbNoSection: 'Без раздела',
  save: 'Сохранить',
  hbNewItem: 'Новый предмет',
  hbEmpty: 'Своих предметов пока нет - создайте первый выше или импортируйте файл.',
  /* The tables' empty state: its button follows the line. */
  hbEmptyTable: 'Своих предметов пока нет.',
  hbSignIn: 'Войдите, чтобы создавать свои предметы.',
  hbTablesSignIn: 'Войдите, чтобы видеть свои предметы в таблицах.',
  hbChipHint: 'Показывать свои предметы',
  hbLoadFailed: 'Не получилось загрузить ваши предметы.',
  edit: 'Изменить',
  hbNotAdded: 'Свой предмет нельзя добавить в этот список.',
  hbNotReady: 'Ваши предметы ещё загружаются - повторите через секунду.',
  quickOwn: 'Свой предмет',
  quickRowHint: 'название и описание, остальное потом в редакторе',
  quickHead: 'Свой предмет в этот список',
  quickNote:
    'Предмет сохранится в «Мои предметы», в «Хоумбрю». Вид, источник и остальное можно задать потом в редакторе.',
  quickAdded: 'Предмет «%s» создан и добавлен в список',
  quickFailed: 'Не получилось создать предмет. Проверьте соединение - текст остался в форме.',
  listEmptyHintOwn: 'Свой предмет можно создать здесь же, кнопкой ниже.',
  hbErrBookGone: 'Этот источник удалили - выберите другой.',
  hbLegend: '* - обязательное поле. Остальное можно заполнить позже.',
  hbKind: 'Вид',
  hbType: 'Тип снаряжения',
  hbSource: 'Источник',
  hbSourceHelp:
    'Источник - ваша книга или сборник: по нему предметы группируются на странице «Мои предметы» и в таблицах. Предмет без источника лежит в «Хоумбрю». В источнике можно завести разделы.',
  hbSourceNew: '+ Новый источник...',
  hbSection: 'Раздел',
  hbSectionNew: '+ Новый раздел...',
  hbName: 'Название',
  hbDesc: 'Описание',
  hbNone: 'Нет',
  hbNoTier: 'Без ранга',
  hbTierHelp:
    'Ранг - этап игры, для которого предмет: 1 - уровень 1, 2 - уровни 2-4, 3 - уровни 5-7, 4 - уровни 8-10. Выберите его сами: по характеристикам ранг не определяется.',
  hbCls: 'Класс',
  hbTrait: 'Характеристика',
  hbRange: 'Дистанция',
  hbDmg: 'Урон',
  hbDie: 'Кость',
  hbDmgDie: 'Кость урона',
  hbDmgHelp:
    'Одна кость и бонус, как в строке оружия в книге: d8+2. Сколько костей бросать, задаёт Мастерство персонажа, поэтому число костей здесь не указывается.',
  hbDmgBonus: 'Бонус к урону',
  hbDt: 'Тип урона',
  hbBurden: 'Хват',
  hbAlt: 'Второй набор характеристик',
  hbAltHint:
    'Для оружия, которое по своему свойству переходит на другие характеристики - например, «Универсальное». Заполните все четыре поля или оставьте набор пустым. Когда набор действует, напишите в описании; на печатной карте он идёт второй полосой урона.',
  hbAltClear: 'Очистить второй набор',
  hbAs: 'Показатель брони',
  hbTh: 'Пороги урона',
  hbThMajor: 'Порог Ощутимого урона',
  hbThSevere: 'Порог Тяжёлого урона',
  hbFixN:
    'Не сохранено: исправьте %n поле.|Не сохранено: исправьте %n поля.|Не сохранено: исправьте %n полей.',
  hbErrName: 'Введите название.',
  hbErrLong: 'Не длиннее %n знаков.',
  hbErrControl: 'Уберите служебные символы.',
  hbErrTier: 'Выберите ранг от 1 до 4.',
  hbErrPick: 'Выберите значение.',
  hbErrDmg: 'Выберите кость d4-d20; бонус, если нужен, - целое число от 1 до 99.',
  hbErrAs: 'Целое число от 0 до 12.',
  hbErrTh: 'Два целых числа от 1 до 99.',
  hbErrThOrder: 'Порог Тяжёлого урона должен быть больше порога Ощутимого урона.',
  hbErrAlt: 'Заполните все четыре поля второго набора или нажмите «Очистить второй набор».',
  hbNotSaved: 'Не сохранено.',
  hbSaveNetwork:
    'Не получилось сохранить: нет связи. Правки остались в форме - нажмите «Сохранить» ещё раз.',
  hbConflict:
    'Этот предмет изменили на другом устройстве, пока форма была открыта. Ваши правки не сохранены.',
  hbSaveMine: 'Сохранить мою версию',
  hbShowNew: 'Показать новую версию',
  hbGone: 'Этот предмет удалили на другом устройстве.',
  hbSaveAsNew: 'Сохранить как новый',
  hbToMyItems: 'К моим предметам',
  hbDropEdits: 'Ваши правки пропадут. Показать новую версию?',
  hbInListsN:
    'Предмет есть в %n списке: изменения появятся в нём сразу, в том числе у игроков по ссылке.|Предмет есть в %n списках: изменения появятся в них сразу, в том числе у игроков по ссылке.|Предмет есть в %n списках: изменения появятся в них сразу, в том числе у игроков по ссылке.',
  hbSaved: 'Сохранено: «%s»',
  hbCreated: 'Предмет «%s» создан',
  hbDeleted: 'Предмет «%s» удалён',
  hbDeletedN: 'Удалено предметов: %n',
  hbDeletingN: 'Удаляем предметы: %n из %m',
  hbSourceCreated: 'Источник «%s» создан',
  hbSectionCreated: 'Раздел «%s» создан',
  hbSourceDeleted: 'Источник «%s» удалён',
  hbSectionDeleted: 'Раздел «%s» удалён',
  hbDeleteFailed: 'Не получилось удалить. Проверьте соединение и попробуйте ещё раз.',
  hbDeleteItem: 'Удалить предмет «%s»? Отменить удаление нельзя.',
  hbDeleteItemInLists:
    'Предмет «%s» есть в %l. Удалить его и убрать из списков? Отменить удаление нельзя.',
  hbListsIn: '%n списке|%n списках|%n списках',
  hbDeleteMany:
    'Удалить предметы (%n)? Они пропадут и из ваших списков. Отменить удаление нельзя.',
  hbDeleteSource: 'Удалить источник «%s»?',
  hbSourceStayN:
    'Его %n предмет останется в «Хоумбрю».|Его %n предмета останутся в «Хоумбрю».|Его %n предметов останутся в «Хоумбрю».',
  hbDeleteSection: 'Удалить раздел «%s»?',
  deleteNoUndo: 'Отменить удаление нельзя.',
  hbSectionStayN:
    'Его %n предмет останется в источнике без раздела.|Его %n предмета останутся в источнике без раздела.|Его %n предметов останутся в источнике без раздела.',
  leaveUnsaved: 'Изменения не сохранены. Уйти со страницы?',
  hbErrSourceName: 'Введите название источника.',
  hbSourceTaken: 'Источник «%s» уже есть.',
  hbErrSectionName: 'Введите название раздела.',
  hbSectionTaken: 'Раздел «%s» уже есть в этом источнике.',
  hbSectionsFull: 'В источнике уже %n разделов - это предел.',
  hbCreateFailed: 'Не получилось создать. Проверьте соединение и попробуйте ещё раз.',
  hbWriteFailed: 'Не получилось сохранить. Проверьте соединение и попробуйте ещё раз.',
  hbBookChanged: 'Источник изменили на другом устройстве. Данные обновлены - повторите.',
  limitHbItems:
    'Достигнут предел своих предметов: %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  limitHbBooks:
    'Достигнут предел источников: %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  hbRelations: 'Связи',
  hbLine: 'Линия улучшений',
  hbLineHelp:
    'Линия улучшений - одно снаряжение на разных рангах, например меч рангов 1-4; карточка рисует лесенку рангов. «Уникальный» - предмет вне линии; «В линии» - предмет встаёт ступенью в линию снаряжения того же типа; «Новая линия» - предмет начинает свою линию, в которую могут встать другие ваши предметы.',
  hbCraftIntoHelp:
    'Предметы, которые делают из этого: например, пробуждённое оружие из спящего. Это не ступени одной линии - для них «Линия улучшений». У выбранного предмета эта связь показывается в «Получается из».',
  hbCraftFromHelp:
    'Предметы, из которых делают этот. У выбранного предмета эта связь показывается в «Улучшается до».',
  hbSetHelp:
    'Комплект - предметы с общим бонусом. Карточка каждого предмета комплекта называет остальные и показывает бонус. Выберите комплект из книги или свой, или создайте новый пунктом «+ Новый комплект...».',
  hbRefsHelp:
    'Карта правил - правило, на которое ссылается предмет: заклинание, черта, противник. Карточка предмета показывает её свёрнутым блоком. Выберите карту из каталога или свою, или создайте новую кнопкой «Новая карта правил».',
  hbLineUnique: 'Уникальный',
  hbLineIn: 'В линии',
  hbLineNew: 'Новая линия',
  hbLinePick: 'Линия, в которую встаёт предмет',
  hbFindLine: 'Найти снаряжение в линии улучшений...',
  hbLineN: 'линия из %n ранга|линия из %n рангов|линия из %n рангов',
  hbLineAlone: 'Линия без других предметов',
  hbFindItem: 'Найти предмет по названию...',
  hbFindMore: 'Добавить ещё: найти предмет...',
  hbFindCard: 'Найти карту: заклинание, черта, противник...',
  hbPickFull: 'Уже %n - больше нельзя',
  hbPickNone: 'Ничего не найдено',
  hbPickMore: 'Ещё %n - уточните запрос',
  hbRemove: 'Убрать: %s',
  hbUpTo8: 'До 8 предметов.',
  hbRefs: 'Карты правил',
  hbRefsHint: 'До 3 карт.',
  hbGoneItem: 'Предмета больше нет',
  hbGoneCard: 'Карты больше нет',
  hbSetNew: '+ Новый комплект...',
  hbNewSet: 'Новый комплект',
  hbNewCard: 'Новая карта правил',
  hbSetName: 'Название комплекта',
  hbSetBonus: 'Бонус комплекта',
  hbCardName: 'Название карты',
  hbCardSub: 'Подзаголовок',
  hbCardSubHint: 'Необязательно. Например: Мудрость · Уровень 1 · Заклинание.',
  hbCardText: 'Текст карты',
  hbCardUrl: 'Ссылка',
  hbCardUrlHint: 'Необязательно: страница с полным текстом правила.',
  hbCreateSet: 'Создать комплект',
  hbCreateCard: 'Создать карту',
  hbSetInlineHint:
    'Комплект создаётся сразу, в источнике этого предмета, и выбирается здесь; бонус хранится один раз и показывается на каждом предмете комплекта.',
  hbCardInlineHint:
    'Карта создаётся сразу, в источнике этого предмета, и выбирается здесь. На предмете - до 3 карт.',
  hbCardEditN:
    'Изменения появятся на %n предмете и в списках, где он лежит.|Изменения появятся на %n предметах и в списках, где они лежат.|Изменения появятся на %n предметах и в списках, где они лежат.',
  hbErrSetBonus: 'Введите бонус комплекта.',
  hbErrCardText: 'Введите текст карты.',
  hbErrUrl: 'Ссылка должна начинаться с https:// и состоять из латиницы без пробелов.',
  hbSetTaken: 'Комплект «%s» уже есть.',
  hbCardTaken: 'Карта правил «%s» уже есть.',
  hbCardChanged: 'Карту изменили на другом устройстве. Данные обновлены - повторите.',
  hbCardGone: 'Эту карту удалили на другом устройстве.',
  hbSetCreated: 'Комплект «%s» создан',
  hbCardCreated: 'Карта правил «%s» создана',
  hbErrLine: 'Выберите предмет из линии или нажмите «Уникальный».',
  hbErrLineType:
    'В этой линии снаряжение другого типа: выберите другую линию или нажмите «Уникальный».',
  hbErrSetOpen: 'Создайте комплект кнопкой «Создать комплект» или нажмите «Отмена».',
  hbErrCardOpen: 'Создайте карту кнопкой «Создать карту» или нажмите «Отмена».',
  hbSourcesN: '%n источник|%n источника|%n источников',
  hbCards: 'Карты',
  hbSets: 'Комплекты',
  hbSetsN: '%n комплект|%n комплекта|%n комплектов',
  hbRefsN: '%n карта правил|%n карты правил|%n карт правил',
  hbCardsN: '%n карта|%n карты|%n карт',
  hbNoSets: 'Комплектов пока нет.',
  hbNoRefs: 'Карт правил пока нет.',
  hbDeleteSet: 'Удалить комплект «%s»? Отменить удаление нельзя.',
  hbDeleteSetUsed:
    'Удалить комплект «%s»? Он указан в %r - там пропадут его название и бонус. Отменить удаление нельзя.',
  hbDeleteRef: 'Удалить карту правил «%s»? Отменить удаление нельзя.',
  hbDeleteRefUsed:
    'Удалить карту правил «%s»? Она указана в %r - там она пропадёт. Отменить удаление нельзя.',
  hbSetDeleted: 'Комплект «%s» удалён',
  hbCardDeleted: 'Карта правил «%s» удалена',
  hbItemsIn: '%n предмете|%n предметах|%n предметах',
  hbDeleteItemRel: 'Предмет «%s» указан в %r. Удалить его? Отменить удаление нельзя.',
  hbDeleteItemInListsRel:
    'Предмет «%s» есть в %l и указан в %r. Удалить его и убрать из списков? Отменить удаление нельзя.',
  limitHbCards:
    'Достигнут предел карт (комплектов и карт правил): %n. Нужно больше - напишите на daggerheart.loot@gmail.com.',
  /* Homebrew files: «Импорт предметов», the «Куда» rows, the bulk move and the downloads
     (docs/specs/FEATURES.md, "Homebrew"). */
  hbImport: 'Импорт предметов',
  hbImportHead: 'Импорт предметов из файла JSON',
  hbImportHintBefore: 'Файл, сохранённый кнопкой «Скачать JSON» или собранный по ',
  hbImportSchema: 'схеме homebrew-v1',
  hbImportHintAfter:
    '), или архив ZIP из «Скачать мои данные». Предметы, которые уже есть, можно пропустить или обновить.',
  hbImportCounts: 'Источников: %b, разделов: %s, карт: %c, предметов: %i.',
  hbImportHeld: 'Предметов и карт, которые уже есть в аккаунте: %n.',
  hbImportWhere: 'Куда положить предметы',
  hbImportNoBook: 'Без источника',
  hbImportToHome: 'В «Хоумбрю»',
  hbImportToHeld: 'В «%s»',
  hbImportToFileNew: 'В «%s» (новый)',
  hbImportToNew: 'Новый источник «%s»',
  hbImportNewName: 'Название нового источника',
  hbImportNoteNew: 'Источник создастся вместе с разделами: %n.',
  hbImportNoteKey: 'Ключ источника совпал с вашим: предметы попадут в него.',
  hbImportNoteName:
    'Источник с таким названием уже есть, но ключ другой (файл сделан заново). По умолчанию предметы попадут в ваш источник.',
  hbImportNoteAdd: 'В источник добавятся разделы: %n.',
  hbImportNoteHome: 'В «Хоумбрю» нет разделов: предметы лягут без раздела.',
  hbImportSameNames: 'Предметов с таким же названием уже есть: %n - они добавятся ещё раз',
  hbImportFull: 'В «%s» будет больше 30 разделов - выберите другой источник.',
  hbImportMoreRows: 'и ещё %n источник|и ещё %n источника|и ещё %n источников',
  hbImportHeldLabel: 'Предметы, карты и источники, которые уже есть',
  hbImportSkip: 'Пропустить',
  hbImportUpdate: 'Обновить',
  hbImportSkipNote: 'Существующие предметы и карты (%n) останутся как есть; новые добавятся.',
  hbImportUpdateNote:
    'Текст и характеристики существующих предметов и карт (%n) заменятся данными из файла, названия источников тоже. Ссылки в списках останутся живыми, замороженные копии не изменятся.',
  hbImportSkipBooksNote:
    'Названия существующих источников останутся как есть; новые разделы добавятся.',
  hbImportUpdateBooksNote:
    'Названия существующих источников заменятся данными из файла; новые разделы добавятся.',
  hbImportUpdateConfirm:
    'Обновить существующие предметы и карты (%n)? Их текст и характеристики заменятся данными из файла. Отменить нельзя.',
  hbImportPosBook: 'Источник %n',
  hbImportPosCard: 'Карта %n',
  hbImportPosItem: 'Предмет %n',
  hbImportUnknownRef:
    '%f «%v» - нет ни в файле, ни в аккаунте, ни в каталоге; связь сохранится, но не покажется',
  hbImportKindDiffers: 'в аккаунте под этим ключом карта другого вида - она пропущена',
  hbImportErrName: 'нет названия - нужен en или ru',
  hbImportErrKey: 'ключ «%v» - hb_ и 16 знаков a-z, 2-7',
  hbImportErrKeyTwice: 'ключ «%v» уже есть в файле',
  hbImportErrBook: 'источника «%v» нет в файле',
  hbImportErrSection: 'раздела «%v» нет в источнике предмета',
  hbImportErrLine: 'eq.line - в этой линии снаряжение другого типа',
  hbImportErrSelf: '%f - предмет ссылается сам на себя',
  hbImportErrDmg: '%f «%v» - урон записывается как d8 или d10+2',
  hbImportErrControl: '%f - служебные символы',
  hbImportErrOrder: 'eq.th - второй порог больше первого',
  hbImportErrMany: '%f - больше %n элементов',
  hbImportErrType: '%f: неверный тип значения',
  hbImportErrEnum: '%f «%v»: недопустимое значение - сверьте с описанием в llms.txt',
  hbImportErrRange: '%f %v - значение вне диапазона',
  hbImportErrPattern: '%f «%v»: неверный формат - сверьте с описанием в llms.txt',
  hbImportErrTwice: '%f - значение повторяется',
  hbImportManyBooks: 'Источников больше %n',
  hbImportManyCards: 'Карт больше %n',
  hbImportManyItems: 'Предметов больше %n',
  hbImportNotFile:
    'Это не файл предметов: нет поля format со значением daggerheart-loot/homebrew.',
  hbImportVersion: 'Файл предметов версии %s: сайт читает версию 1.',
  hbImportNoVersion: 'В файле нет поля version. Сайт читает версию 1.',
  hbImportEmpty: 'В файле нет ни источников, ни карт, ни предметов.',
  hbImportZipNone: 'В архиве нет файла homebrew.json.',
  hbImportZipMany: 'В архиве несколько файлов homebrew.json: распакуйте его и выберите нужный.',
  hbImportZipPacked: 'Архив сжат другой программой: распакуйте его и выберите homebrew.json.',
  hbImportZipLists: 'Файл lists.json из архива импортируется на странице «Мои списки».',
  hbImportDone: 'Импортировано предметов: %n',
  hbImportDoneUpdated: 'обновлено: %n',
  hbImportDoneSkipped: 'пропущено: %n',
  hbImportDoneBooks: 'новых источников: %n',
  hbImportDoneCards: 'новых карт: %n',
  hbImportFailed: 'Не получилось импортировать. Проверьте соединение и попробуйте ещё раз.',
  hbImportRefused: 'Сервер не принял файл. Обновите страницу и выберите файл снова.',
  hbImportChunkFailed: 'Не получилось загрузить импорт.',
  hbMove: 'Переместить (%n)',
  hbMoveGo: 'Переместить',
  hbMoving: 'Перемещаем...',
  hbMoveHere: 'Отмеченные предметы уже здесь.',
  hbMovedN: 'Перемещено предметов: %n',
  hbMoveFailed: 'Не получилось переместить. Проверьте соединение и попробуйте ещё раз.',
  hbMoveChanged: 'Предметы изменили на другом устройстве. Данные обновлены - повторите.',
  hbMoveBookGone:
    'Этого источника больше нет - его удалили на другом устройстве. Выберите другой источник.',
  hbMoveSectionGone:
    'Этого раздела больше нет - его удалили на другом устройстве. Выберите другой раздел.',
  hbMoveRefused: 'Сервер не принял перемещение. Обновите страницу и попробуйте ещё раз.',

  /* The index's selection and exports, and the import from a file
     (docs/specs/FEATURES.md, "Lists"). */
  exportJson: 'Скачать JSON',
  exportOverBounds: 'Этот файл нельзя импортировать целиком.',
  exportBig: 'Он больше 5 МБ: экспортируйте списки частями.',
  exportHomebrewBig:
    'Файл homebrew.json больше 5 МБ: скачайте источники по одному на странице «Мои предметы».',
  exportManyLists: 'В нём больше 1000 списков: экспортируйте их частями.',
  exportLongLists: 'В списках %s позиций больше 5000: разделите такие списки.',
  exportHomebrewSkippedN:
    '%n свой предмет не попал в файл: его больше нет в аккаунте.|%n своих предмета не попали в файл: их больше нет в аккаунте.|%n своих предметов не попали в файл: их больше нет в аккаунте.',
  pickList: 'Выбрать: %s',
  deleteListsConfirm:
    'Удалить списки (%n): %s? Ссылки для игроков и мастера на них перестанут работать. Отменить удаление нельзя.',
  listsDeleted: 'Удалено списков: %n',
  andMore: 'и ещё %n',
  requestLinesMoreN: 'и ещё %n позиция|и ещё %n позиции|и ещё %n позиций',
  requestsMoreN: 'и ещё %n запрос|и ещё %n запроса|и ещё %n запросов',
  /* `%k` is the number of ticked lines the reader sent. */
  requestLinesMax:
    'В запросе может быть не больше %n позиции, а отмечено %k. Снимите лишние отметки и отправьте ещё раз.|В запросе может быть не больше %n позиций, а отмечено %k. Снимите лишние отметки и отправьте ещё раз.|В запросе может быть не больше %n позиций, а отмечено %k. Снимите лишние отметки и отправьте ещё раз.',
  importOpen: 'Импорт из файла',
  importHead: 'Импорт из файла JSON',
  importPick: 'Выбрать файл...',
  importHintBefore: 'Файл JSON, сохранённый кнопкой «Скачать JSON» или собранный по ',
  importSchema: 'схеме import-v1',
  importHintMid: ' (',
  importLlms: 'описание для ИИ-помощников',
  importHintAfter:
    '), или архив ZIP из «Скачать мои данные». Списки добавятся как новые; существующие не изменятся.',
  importPreview: 'Списков: %l, позиций: %n.',
  importSkippedN: 'Пропущено позиций: %n.',
  importWillN:
    '%n позиция будет импортирована|%n позиции будут импортированы|%n позиций будут импортированы',
  importListEmpty: 'без позиций',
  importNoName: '(без названия)',
  importPos: 'Позиция %n',
  importSkipUnknown: 'пропущена - такой записи нет в данных',
  importSkipRepeat: 'пропущена - уже есть в позиции %n',
  importNameTaken: 'Список с таким названием уже есть в аккаунте - появится второй',
  importZipOther: 'В архиве есть файлы, которые эта версия не читает: %s.',
  importGo: 'Импортировать',
  importDone: 'Импортировано списков: %n',
  importTooBig: 'Файл больше 5 МБ.',
  importZipTooBig: 'Архив больше 10 МБ.',
  importTooSlow: 'Файл слишком большой для одного импорта: разделите его на несколько.',
  importNotJson: 'Это не файл JSON.',
  importNotBundle: 'Это не файл списков: нет поля format со значением daggerheart-loot/lists.',
  importVersion: 'Неизвестная версия формата: %s. Приложение читает версии 1 и 2.',
  importNoVersion: 'В файле нет поля version. Приложение читает версии 1 и 2.',
  importEmpty: 'В файле нет списков.',
  importZipNoLists: 'В архиве нет файла lists.json.',
  importZipManyLists: 'В архиве несколько файлов lists.json: распакуйте его и выберите нужный.',
  importZipPacked: 'Архив сжат другой программой: распакуйте его и выберите lists.json.',
  importZipHomebrew: 'Файл homebrew.json из архива импортируется на странице «Мои предметы».',
  importRefused:
    'Сервер не принял файл: данные в аккаунте изменились. Нажмите «Импортировать» ещё раз.',
  importFrozenN:
    'Своих предметов, которых нет в аккаунте: %n - они сохранятся копиями. Чтобы они остались живыми, сначала импортируйте предметы на странице «Мои предметы».',
  importMoreLists: 'и ещё %n список|и ещё %n списка|и ещё %n списков',
  importNotZip: 'Это не архив данных.',
  importErrors: 'В файле ошибки - ничего не импортировано. Исправьте их и выберите файл снова.',
  importFieldName: 'Название',
  importErrMissing: '%f: обязательное поле отсутствует',
  importErrName: 'Название: пустое или отсутствует',
  importErrType: '%f «%v»: неверный тип - нужен %s',
  importErrNotObject: '«%v»: неверный тип - нужен объект JSON',
  importErrId: 'id «%v»: не id записи - только латинские буквы, цифры, _ и -, до 64 символов',
  importErrHbId: 'id «%v»: не ключ своего предмета - hb_ и 16 знаков a-z, 2-7',
  importErrSnapshot: 'snapshot: не копия предмета - сверьте поля с описанием в llms.txt',
  importErrLong: '%f: длиннее %n символов',
  importErrRange: '%f %v - значение вне диапазона %s',
  importErrEnum: '%f «%v»: допустимые значения - %s',
  importErrExtra: 'неизвестное поле %f',
  importErrManyLists: 'Списков больше %n',
  importErrManyEntries: 'Позиций больше %n',
  importErrMoreList: '...и ещё %n в этом списке',
  importErrMore: '...и ещё %n ошибка|...и ещё %n ошибки|...и ещё %n ошибок',

  /* Share links of an account list and the shared page `#/s/<token>`
     (docs/specs/FEATURES.md, "Account and browser lists"). */
  shareLinkPlayers: 'Ссылка для игроков',
  shareLinkGm: 'Ссылка для мастера',
  shareCopy: 'Скопировать',
  shareCreate: 'Создать ссылку',
  shareDelete: 'Удалить ссылку',
  shareStopped: 'Ссылка удалена',
  shareHint:
    '«Удалить ссылку» закрывает доступ: по удалённой ссылке список больше не откроется. «Создать ссылку» даёт новую. Ссылка для мастера показывает и заметки «Только для мастера» - давайте её только мастерам.',
  shareLoadFailed: 'Не получилось загрузить ссылки.',
  shareCreated: 'Ссылка создана.',
  shareDeleted: 'Ссылка удалена: по ней список больше не откроется.',
  shareFailed: 'Не получилось изменить ссылку. Проверьте соединение и попробуйте ещё раз.',
  gmShareCopied: 'Ссылка для мастера скопирована - в ней есть заметки мастера',
  updatedAgo: 'Обновлено %s',
  updatedNow: 'Обновлено только что',
  ownList: 'Это ваш список.',
  ownListEdit: 'Открыть для правки',
  shareGone: 'Список больше не доступен',
  shareGoneSub: 'Владелец удалил эту ссылку или список.',
  sharedFailed: 'Список не загрузился',
  sharedFailedSub: 'Проверьте соединение и нажмите «Повторить».',
  listUpdated: 'Список обновлён',
  cloneFailed:
    'Не получилось сохранить список себе. Проверьте соединение и попробуйте ещё раз.',
  legacyLinks:
    'Ссылки вида #/l/ перестанут открываться %d. Сохраните список себе, чтобы не потерять его.',

  /* Purchase requests: the reader's send and flow b, the owner's panel and
     the index line (docs/specs/FEATURES.md, "Account and browser lists").
     `%w` is the count asked for, `%h` the stock. */
  requestSend: 'Сообщить владельцу',
  requestSending: 'Отправляем...',
  requestSentDone: 'Запрос отправлен',
  requestSent: 'Запрос отправлен владельцу списка.',
  requestSentOwner: 'Владелец получил запрос.',
  requestRate: 'Слишком много запросов по этой ссылке: подождите минуту.',
  requestPending: 'У владельца уже %s без ответа. Попробуйте позже.',
  requestsN: '%n запрос|%n запроса|%n запросов',
  requestStale: 'Список изменился. Проверьте выбор и отправьте снова.',
  requestNetwork: 'Не получилось отправить. Проверьте соединение и попробуйте ещё раз.',
  requestRefused: 'Сервер не принял запрос.',
  notifyQuestion: 'Сообщить владельцу списка, что вы взяли эти предметы?',
  notifyYes: 'Сообщить',
  notifyRemember: 'Запомнить ответ',
  requestsHead: 'Запросы (%n)',
  requestByPlayers: 'По ссылке для игроков',
  requestByGm: 'По ссылке для мастера',
  requestJustNow: 'только что',
  requestExpires: 'истечёт %s',
  requestOf: '×%w из %h',
  requestNotInList: 'нет в списке',
  requestApply: 'Принять',
  requestApplyAvailable: 'Принять доступное',
  requestDecline: 'Отклонить',
  requestShort: 'Не хватает: %s. Ничего не списано.',
  requestShortLine: '%s - просят %w, есть %h',
  requestsDecided: 'Решённые в этот раз (%n)',
  requestsHide: 'Скрыть',
  requestsHideName: 'Скрыть решённые запросы',
  requestAppliedLine: 'принят',
  requestTakenLine: 'принят: списано %n шт.',
  requestDeclinedLine: 'отклонён',
  requestApplied: 'Запрос принят',
  requestTaken: 'Запрос принят: списано %n шт.',
  requestDeclined: 'Запрос отклонён',
  requestDecidedElsewhere: 'Этот запрос уже решён на другом устройстве.',
  requestExpired: 'Этот запрос истёк: прошёл час без ответа.',
  requestActFailed:
    'Не получилось ответить на запрос. Проверьте соединение и попробуйте ещё раз.',
  requestNew: 'Новый запрос',
  requestsWaitN: '%n запрос ждёт ответа|%n запроса ждут ответа|%n запросов ждут ответа',

  /* Browser lists moved into the account, and read-only after the cutoff
     (docs/specs/FEATURES.md, "Account and browser lists"). `%d` is the
     cutoff date (`legacyDateText`). */
  quoted: '«%s»',
  movedNotice: 'Списки из этого браузера перенесены в ваш аккаунт: %s.',
  movedBad:
    'В этом браузере осталась повреждённая копия списков: её не получилось прочитать и перенести. Если в ней было что-то важное, напишите на daggerheart.loot@gmail.com.',
  moving: 'Переносим списки в аккаунт...',
  moveFailed: 'Не все списки перенесены: нет связи. Попробуем при следующем открытии.',
  moveAttention: 'Не перенесён: %s.',
  moveAttentionWhy: 'Сервер не принял список. Напишите на daggerheart.loot@gmail.com.',
  moveHeldWhy:
    'Копия в аккаунте не совпала со списком. Напишите на daggerheart.loot@gmail.com.',
  localOnlyMove:
    'Войдите до %d - и они перенесутся в аккаунт. После этой даты приложение перестанет их показывать.',
  moveBannerLead: 'Ваши списки хранятся только в этом браузере.',
  moveBannerSignIn: 'Войти и перенести списки',
  moveBannerHide: 'Скрыть напоминание',
  localReadOnlyTitle: 'Списки в этом браузере только для чтения с %d.',
  localReadOnly:
    'Войдите - они перенесутся в аккаунт, и их снова можно будет править. Скопировать текст и напечатать можно и так.',
  linkRetired: 'Ссылки такого вида перестали открываться %d.',
  linkRetiredSub: 'Попросите у отправителя новую ссылку или войдите, чтобы собрать список.'
} as const;

/** Every key the interface has. Derived, so the two sides cannot drift. */
export type Dict = Record<keyof typeof ru, string>;

/** A toast's text, built from the dictionary and the language on screen
 *  each time the toast is drawn (docs/specs/I18N.md, "Rules"). */
export type Msg = (t: Dict, lang: Lang) => string;

const en: Dict = {
  docTitle: 'Daggerheart Loot Generator',
  skipToContent: 'Skip to content',
  sectionsLabel: 'Sections',
  langLabel: 'Language',
  close: 'Close',

  std: 'Standard rules',
  alt: 'Alt. tables',
  wondrous: 'Wondrous',
  dread: 'Dread',
  voa: 'Vault of Ages',
  dv: "Dragon's Vault",
  community: 'Communities',
  tables: 'Tables',
  lists: 'Lists',
  search: 'Search',

  item: 'Item',
  cons: 'Consumable',
  craftInto: 'Upgrades to',
  craftFrom: 'Made from',
  setLabel: 'Set',

  copyName: 'Copy name',
  copyText: 'Copy text',
  copyImg: 'Copy image',
  sImg: 'Image',
  sText: 'Text',
  openPage: 'Page',
  showInTable: 'show in the table',
  rollNo: 'roll',

  srcCore: 'Core',
  srcHnf: 'Hope & Fear',
  srcWond: 'Wondrous',
  srcDread: 'Dread',
  srcVoa: 'Vault of Ages',
  srcDv: "Dragon's Vault",
  srcFrame: 'Frame',
  srcComm: 'Communities',
  copyLink: 'Copy link',
  sendAll: 'Share',
  nameCopied: 'Name copied',
  imgCopied: 'Image copied',
  textCopied: 'Text copied',
  linkCopied: 'Link copied',
  copyFailed: 'Could not copy',
  rollCopied: 'Options copied',
  imgTainted: 'Could not copy the image - copied the text instead',
  imgSaved: 'Image saved',
  imgFailed: 'Could not save the image',

  roll: 'Roll',
  randomIn: 'Random',
  rollResult: 'Roll result',
  stepDown: 'One lower',
  stepUp: 'One higher',

  footBefore:
    "Data: Daggerheart Core Set, Hope & Fear, Wondrous Loot, Dread GM Toolbox, Vault of Ages, The Dragon's Vault, Community Magic Items, Alternate Loot & Consumable Tables. Russian text: daggerheart.su and custom material. Daggerheart © Darrington Press. This product includes materials from the Daggerheart System Reference Document 2.0, © Critical Role, LLC. under the terms of the Darrington Press Community Gaming (DPCGL) License. More information can be found at ",
  footLink: 'daggerheart.com',
  footAfter: '. There are no previous modifications by others.',
  footSummary: 'Daggerheart © Darrington Press - DPCGL - Sources and licence',
  footNavLabel: 'Site pages',
  installLink: 'Install as an app',
  privacyLink: 'Privacy',
  termsLink: 'Terms of use',

  pageWondrous: 'Wondrous Loot',
  pageDread: 'Dread GM Toolbox',
  pageVoa: 'Vault of Ages',
  pageDv: "The Dragon's Vault",
  pageCommunity: 'Community items',
  pageStd: 'Standard rules',
  subStd: 'A roll over the core book and the Hope & Fear tables.',
  common: 'Common',
  uncommon: 'Uncommon',
  rare: 'Rare',
  veryRare: 'Very rare',
  legendary: 'Legendary',
  source: 'Source',
  keepOneSource: 'At least one source has to stay on',
  filter: 'Type',
  fItems: 'Items',
  fCons: 'Consumables',
  fEquip: 'Equipment',
  keepOneKind: 'At least one type has to stay on',
  or: 'OR',
  copyRoll: 'Copy every option',
  subWondrous: 'Enter your roll result, or pick a random entry.',
  subVoa: 'Pick a section of the book and roll within it.',
  subCommunity: 'Pick an origin and roll d10.',

  pageAlt: 'Alternate tables',
  subAlt: 'A Duality Dice roll over both books merged into one set of tables.',
  rarity: 'Rarity',
  hopeDie: 'Hope Die',
  fearDie: 'Fear Die',
  rollDuality: 'Roll the dice',
  hope: 'Hope',
  fear: 'Fear',
  crit: 'Critical success!',
  critSub:
    'The player takes any entry from this rarity table. The GM may allow bumping up one rarity.',
  openTable: 'Open table',
  openItems: 'Items table',
  openCons: 'Consumables table',
  bumpUncommon: 'Bump to Uncommon',
  bumpRare: 'Bump to Rare',
  bumpVeryRare: 'Bump to Very rare',
  bumpLegendary: 'Bump to Legendary',

  voaSection: 'Section',
  voaArtifact: 'Artifacts',
  voaCursed: 'Cursed objects',
  voaArtifact1: 'Artifact',
  voaCursed1: 'Cursed object',
  unique: 'Unique',
  uniqueHint: 'Printed at a single tier - this one has no upgrade ladder',
  homeHint: 'Open this section on start',
  homeOn: 'Opens on start',
  helpHint: 'How this works',
  fieldHelp: 'Help: %s',
  rollLabelFor: 'Roll result',
  communityLabel: 'Community',

  notFound: 'Item not found',
  notFoundSub: 'The link may be out of date, or the data has changed.',
  noData: 'The data did not load. Reload the page.',
  pageError: 'Something went wrong on this page.',
  reloadPage: 'Reload the page',

  tier: 'Tier',
  eqTh: 'Thresholds',
  eqScore: 'Armor',
  eqClass: 'Class',
  eqTrait: 'Trait',
  eqRange: 'Range',
  eqBurden: 'Burden',
  eqLineF: 'Line',

  pcDmg: 'Damage',
  pcTrait: 'Trait',
  pcRange: 'Range',
  pcArmor: 'Armor',
  thLight: 'Minor damage',
  thMajor: 'Major damage',
  thSevere: 'Severe damage',

  grpEquipment: 'Equipment',
  grpOther: 'Other',
  subStarting: 'Starting',
  subFrames: 'Frames',
  subWeapon: 'Weapons',
  subSecondary: 'Secondary',
  subArmor: 'Armor',

  subTables: 'Every table in full, weapons and armor included - browse, filter and open cards.',
  subLists: 'Collect loot into a list and send it to your players as a single link.',
  subSearch:
    'Search all 1272 entries at once - loot, consumables and equipment, in Russian and English.',
  subSearchOwn: 'And %n item of your own.|And %n items of your own.',

  searchPh: 'Search by name or description…',
  tableLink: 'Link to this table',
  tableLinkCopied: 'Table link copied',
  view: 'View',
  viewList: 'List',
  viewGrid: 'Grid',
  nothing: 'Nothing found',
  startTyping:
    'Start typing. Several words match in any order; "a phrase in quotes" matches exactly.',
  selectAll: 'Select all',
  selected: 'Selected',
  selectedN: 'Selected %n item|Selected %n items',
  itemsN: '%n item|%n items',
  listsN: '%n list|%n lists',
  ofLimit: '%s of %m',
  clearSel: 'Clear selection',
  selRegion: 'Selected records',
  copySel: 'Copy',
  selCopied: 'Selection copied',

  filters: 'Filters',
  kindF: 'Type',
  frameF: 'Frame',
  commF: 'Community',
  anyValue: 'any',
  outOf: 'of',
  dropValue: 'Remove from the filter',
  resetAll: 'Reset all',
  filterLink: 'Filter link',
  filterLinkCopied: 'Filter link copied',

  copySection: 'Copy a link to this section',
  sectionLinkCopied: 'Section link copied',

  addToList: 'Add to list',
  addTo: 'Add to',
  inLists: 'Sits in lists',
  newList: 'New list',
  listNamePh: 'For example: dragon hoard',
  create: 'Create',
  cancel: 'Cancel',
  findList: 'Find a list',
  showMore: 'Show more',
  addedTo: 'Added to "%s"',
  removedFrom: 'Removed from "%s"',
  nameFirst: 'Give the list a name first',
  untitled: 'Untitled',
  saveFailed:
    'Could not save: the browser refused the write - local storage is blocked or full',
  sharedList: 'A list from another player',
  saveShared: 'Save to my lists',
  toStart: 'Home',
  print: 'Print',
  printHint: 'Lay these out for printing: nine to an A4 sheet',
  printColor: 'Colour',
  printBW: 'Black and white',
  printStd: 'Standard',
  printCompact: 'Compact',
  printSize: 'Card size',
  printNow: 'Send to printer',
  printLink: 'Link to this set',
  printTitle: 'Printing cards',
  printSub: 'Cards: %n. A4 sheets: %p. Card size 63×88 mm - the size of a playing card.',
  printSubCompact: 'Cards: %n. A4 sheets: %p. Card size 44×63 mm - sixteen to a sheet.',
  printNote:
    'In the print dialog pick A4, portrait, and margins "none". The sheet is light on purpose: it reads on a black-and-white printer and does not drain the cartridge.',
  printEmpty: 'Nothing to print: the address holds no items.',
  back: 'Back',
  printTooMany:
    'One run prints %n cards; the remaining %d did not make it onto a sheet. Split the set in two.',
  homeSet: 'The app will open on this section',
  homeReset: 'The app will open on the standard rules again',

  dismiss: 'Dismiss',
  readMore: 'more',
  listCreated: 'List "%s" created',
  noLists: 'No lists yet - create one above.',
  share: 'Share',
  del: 'Delete',
  listEmpty: 'The list is empty',
  noStorageTitle: 'The browser is blocking local storage.',
  noStorage:
    'Lists will not survive a page reload. This usually happens in private mode or when the site is denied storage. Sharing a link still works.',
  badStorageTitle: 'The saved lists could not be read.',
  badStorage:
    'Something else on this site - another build, a browser extension, or another tab - seems to have written them. The original content was kept under a separate key rather than lost; further changes save again from a clean list.',
  localOnlyTitle: 'Lists live in this browser only.',
  localOnly:
    'Clearing site data, a private window or another device, and the lists are gone. To keep one, press "Your own link": the whole list is encoded in the address and comes back from it entire, both notes included. That link is for you alone — it carries whatever you wrote under "GM only". Send players the "Players\' link" or the result of "Copy text": only what is written under "For players" goes there. The browser\'s own address bar holds the players\' link too, so copying it from there is safe. Do remember that a link is a snapshot: it holds the list as it was when you copied it. Add an entry or edit a note and save the link again.',
  deleteConfirm: 'Delete the list "%s"? This cannot be undone.',
  listDeleted: 'List "%s" deleted',
  playersLinkCopied: "Players' link copied — it carries no GM notes",
  badShare: 'The link is damaged or was built from a different data version.',
  droppedItems:
    'Skipped %n item - no longer in the data|Skipped %n items - no longer in the data',

  rename: 'List name',
  sharePlayers: "Players' link",
  shareGm: 'Your own link',
  gmLinkCopied: 'Link with every note copied — this one is for you',
  listCopied: 'List copied',
  listEmptyHint:
    'Nothing here yet. Open Tables or Search, tick what you need and press "Add to list" - or do it straight from an item card.',
  listNotFound: 'List not found',
  listNotFoundSub: 'It may have been deleted, or it lives in another browser.',
  rollBy: 'Roll on this list',
  rollHint: 'Roll a die and type the result - or press the button',
  clear: 'Clear',
  note: 'Note',
  listNote: 'Notes',
  noteHead: 'Note',
  notePub: 'For players',
  noteHid: 'GM only',
  notePubHint: "travels with the text and the players' link",
  noteHidHint: 'stays with you',
  listNotePhPub: 'e.g. the shop is shut until morning',
  listNotePhHid: 'e.g. entries 9-10 are kept under the counter',
  notePhPub: 'What it looks like, what is known about it',
  notePhHid: 'Homebrew, the catch, what only the GM knows',
  noteClear: 'Clear the note',
  noteCleared: 'Note cleared',
  qty: 'Qty',
  gold: 'Gold',
  position: 'Position in the list',
  dragHint: 'Drag to reorder',
  removeItem: 'Remove from the list',
  removedItem: '"%s" removed from the list',
  movedItem: '"%s" - position %n of %m',
  undo: 'Undo',
  pickAll: 'Select all',
  total: 'Total',
  unpricedN: 'no price: %n',
  pickQty: 'Take',
  pickQtyOf: 'Take: %s',
  pickOf: 'of %n',
  pickMin: 'Min',
  pickMax: 'Max',
  pickMinOf: 'Min, take 1: %s',
  pickMaxOf: 'Max, take all: %s',
  pcsN: '%n pcs',
  eachPrice: '%s each',
  moneyAs: 'Price display',
  money_bag: 'As in the book',
  money_coin: 'In coins',
  goldUnit: 'gp',
  batchMoney: 'Prices',
  batchNoPrice: 'Clear price',
  repricePct: 'Change by, %',
  repriceDown: 'Discount',
  repriceUp: 'Mark up',
  repriceHint: 'Minus discounts, plus marks up. Counted from the current price.',
  repriceDone: 'Prices recalculated',
  repriceUndo: 'Undo',
  batchDeleted: 'Removed from the list',
  guessApply: 'Set these prices',
  guessWhy:
    'The book has no prices: Core (p. 105) leaves them to the GM. These magnitudes come from the community spreadsheet - by tier for equipment, by rarity for loot. Not canon, a starting point; the selected rows will have their prices overwritten.',
  guessNoTier: 'nothing to go on',
  guessNoRarity: 'no rarity given',
  guessDone: 'Prices set',

  /* The account */
  account: 'Account',
  signIn: 'Sign in',
  accountSub: 'Display, sign-in methods, signing out and your data.',
  menuLabel: 'Account menu',
  menuLists: 'My lists',
  displayHead: 'Display',
  displayLead:
    'These settings apply on all your devices. A tables view or a print layout picked on its own page is kept only until the page reloads.',
  keepBefore: 'Only until the page reloads. To keep it, change it in ',
  keepLink: 'your account settings',
  keepAfter: '.',
  displayHome: 'Section on start',
  printCompactBox: 'Compact sheet',
  displayNotify: "Adding from someone else's list",
  notifyAsk: 'Ask',
  notifyAlways: 'Notify the owner',
  notifyNever: "Don't notify",
  notifyHint: "When you add items from someone else's list to yours, notify its owner?",
  signInLead:
    'Sign in to have your data on all your devices. Everything else works without signing in.',
  signInWith: 'Sign in with %s',
  consentBefore: 'By signing in you accept the ',
  consentTerms: 'terms',
  consentMid: ' and the ',
  consentPrivacy: 'privacy policy',
  consentAfter: '.',
  signedInAs: 'Signed in as',
  via: 'with %s',
  providers: 'Connected providers',
  notConnected: 'not connected',
  connect: 'Connect %s',
  redirecting: 'Redirecting to %s...',
  disconnect: 'Disconnect',
  onlyMethod:
    '%s is your only sign-in method, so it cannot be disconnected. Connect another one first.',
  alreadyLinked: 'This %s account is already used by another account.',
  signOutHead: 'Sign out',
  signOut: 'Sign out',
  signOutAll: 'Sign out everywhere',
  signOutAllHint:
    '"Sign out everywhere" also ends the session on your other phones and computers.',
  deleteHead: 'Delete account',
  deleteHint: 'The account and all the data linked to it will be deleted for good.',
  deleteOpen: 'Delete account...',
  deleteTypeWord: 'To confirm, type the word',
  deleteWord: 'delete',
  deleteFinal: 'Delete for good',
  signedOut: 'You are signed out.',
  accountDeleted: 'The account is deleted.',
  accountFailed: 'That did not work. Check the connection and try again.',
  yourData: 'Your data',
  yourDataHint:
    'Everything your account holds, in one ZIP archive: lists.json with your lists and, when you have items of your own, homebrew.json with them, their sources and cards. To move everything into another account, import the archive on the My items page first, then on the My lists page: up to 1000 lists and 1000 own items at a time.',
  exportData: 'Download my data (ZIP)',

  groupAccount: 'Your account',
  groupBrowser: 'This browser',
  noCloudLists: 'No lists in your account yet - create one above.',
  cloudLoading: 'Loading...',
  cloudLoadFailed: 'Could not load the lists in your account.',
  retry: 'Retry',
  editedAgo: 'edited %s',
  editedNow: 'edited just now',
  saving: 'Saving...',
  savedState: 'Saved',
  notSaved: 'Not saved',
  signInToCreate:
    'Sign in to create lists: they are kept in your account and open on any device.',
  signInToCreateShort: 'Sign in to create a list.',
  signInToSave: 'Sign in and the list is saved to your account.',
  signInToOpen: 'If this list is in your account, sign in to open it.',
  deleteCloudConfirm:
    'Delete the list "%s"? Its player and GM links will stop working. This cannot be undone.',
  limitLists:
    'You have reached the limit of %n lists. Need more? Write to daggerheart.loot@gmail.com.',
  limitEntries:
    'This list has reached its limit of %n entries. Need more? Write to daggerheart.loot@gmail.com.',
  limitSnapshots:
    "This list has reached its limit of %n KB of copies of other players' items. Need more? Write to daggerheart.loot@gmail.com.",
  limitOther: 'A limit has been reached: %n. Need more? Write to daggerheart.loot@gmail.com.',
  writeRefused:
    'The change was not saved: the server refused it. The list from your account is shown.',

  myItems: 'My items',
  subHomebrew:
    'Items that are not in the books: search finds them with the catalog, they appear in the tables and go into lists.',
  srcHomebrew: 'Homebrew',
  hbTag: '%s (HB)',
  hbMark: 'HB',
  relLess: 'show less',
  hbSources: 'Sources',
  hbItemsN: '%n item|%n items',
  hbSectionsN: '%n section|%n sections',
  hbSectionsBtn: 'Sections',
  hbRename: 'Rename',
  hbNewSource: 'New source',
  hbNewSection: 'New section',
  hbNoSection: 'No section',
  save: 'Save',
  hbNewItem: 'New item',
  hbEmpty: 'No items of your own yet - create the first one above or import a file.',
  hbEmptyTable: 'No items of your own yet.',
  hbSignIn: 'Sign in to create your own items.',
  hbTablesSignIn: 'Sign in to see your own items in the tables.',
  hbChipHint: 'Show your own items',
  hbLoadFailed: 'Could not load your items.',
  edit: 'Edit',
  hbNotAdded: 'Your own item cannot go into this list.',
  hbNotReady: 'Your items are still loading - try again in a second.',
  quickOwn: 'Own item',
  quickRowHint: 'a name and a description, the rest later in the editor',
  quickHead: 'An own item for this list',
  quickNote:
    'The item is saved in "My items", under "Homebrew". Its kind, source and the rest can be set later in the editor.',
  quickAdded: 'Item "%s" created and added to the list',
  quickFailed: 'Could not create the item. Check the connection - the text stays in the form.',
  listEmptyHintOwn: 'You can also make an item of your own here, with the button below.',
  hbErrBookGone: 'This source was deleted - choose another one.',
  hbLegend: '* - required field. The rest can be filled in later.',
  hbKind: 'Kind',
  hbType: 'Equipment type',
  hbSource: 'Source',
  hbSourceHelp:
    'A source is your own book or collection: "My items" and the tables group items by it. An item with no source is kept under "Homebrew". A source can hold sections.',
  hbSourceNew: '+ New source...',
  hbSection: 'Section',
  hbSectionNew: '+ New section...',
  hbName: 'Name',
  hbDesc: 'Description',
  hbNone: 'None',
  hbNoTier: 'No tier',
  hbTierHelp:
    'The tier is the stage of play the item is for: 1 - level 1, 2 - levels 2-4, 3 - levels 5-7, 4 - levels 8-10. Choose it yourself: the tier is never worked out from the stats.',
  hbCls: 'Class',
  hbTrait: 'Trait',
  hbRange: 'Range',
  hbDmg: 'Damage',
  hbDie: 'Die',
  hbDmgDie: 'Damage die',
  hbDmgHelp:
    "One die and a bonus, as a weapon line in the book prints them: d8+2. The character's Proficiency sets how many dice to roll, so the form takes no dice count.",
  hbDmgBonus: 'Damage bonus',
  hbDt: 'Damage type',
  hbBurden: 'Burden',
  hbAlt: 'Second stat set',
  hbAltHint:
    'For a weapon whose feature switches it to other stats, for example Versatile. Fill in all four fields or leave the set empty. Say in the description when the set applies; the print card shows it as a second damage strip.',
  hbAltClear: 'Clear the second set',
  hbAs: 'Armor Score',
  hbTh: 'Damage thresholds',
  hbThMajor: 'Major threshold',
  hbThSevere: 'Severe threshold',
  hbFixN: 'Not saved: fix %n field.|Not saved: fix %n fields.',
  hbErrName: 'Enter a name.',
  hbErrLong: 'At most %n characters.',
  hbErrControl: 'Remove the control characters.',
  hbErrTier: 'Choose a tier from 1 to 4.',
  hbErrPick: 'Choose a value.',
  hbErrDmg: 'Choose a die d4-d20; a bonus, if any, is a whole number from 1 to 99.',
  hbErrAs: 'A whole number from 0 to 12.',
  hbErrTh: 'Two whole numbers from 1 to 99.',
  hbErrThOrder: 'The Severe threshold must be greater than the Major threshold.',
  hbErrAlt: 'Fill in all four fields of the second set, or press "Clear the second set".',
  hbNotSaved: 'Not saved.',
  hbSaveNetwork:
    'Could not save: no connection. Your edits are still in the form - press "Save" again.',
  hbConflict:
    'This item was changed on another device while the form was open. Your edits are not saved.',
  hbSaveMine: 'Save my version',
  hbShowNew: 'Show the new version',
  hbGone: 'This item was deleted on another device.',
  hbSaveAsNew: 'Save as new',
  hbToMyItems: 'To my items',
  hbDropEdits: 'Your edits will be lost. Show the new version?',
  hbInListsN:
    'The item is in %n list: changes appear there at once, for players with a link too.|The item is in %n lists: changes appear there at once, for players with a link too.',
  hbSaved: 'Saved: "%s"',
  hbCreated: 'Item "%s" created',
  hbDeleted: 'Item "%s" deleted',
  hbDeletedN: 'Items deleted: %n',
  hbDeletingN: 'Deleting items: %n of %m',
  hbSourceCreated: 'Source "%s" created',
  hbSectionCreated: 'Section "%s" created',
  hbSourceDeleted: 'Source "%s" deleted',
  hbSectionDeleted: 'Section "%s" deleted',
  hbDeleteFailed: 'Could not delete. Check the connection and try again.',
  hbDeleteItem: 'Delete the item "%s"? This cannot be undone.',
  hbDeleteItemInLists:
    'The item "%s" is in %l. Delete it and remove it from the lists? This cannot be undone.',
  hbListsIn: '%n list|%n lists',
  hbDeleteMany: 'Delete the items (%n)? They also leave your lists. This cannot be undone.',
  hbDeleteSource: 'Delete the source "%s"?',
  hbSourceStayN: 'Its %n item stays in "Homebrew".|Its %n items stay in "Homebrew".',
  hbDeleteSection: 'Delete the section "%s"?',
  deleteNoUndo: 'This cannot be undone.',
  hbSectionStayN:
    'Its %n item stays in the source with no section.|Its %n items stay in the source with no section.',
  leaveUnsaved: 'The changes are not saved. Leave the page?',
  hbErrSourceName: 'Enter a source name.',
  hbSourceTaken: 'The source "%s" already exists.',
  hbErrSectionName: 'Enter a section name.',
  hbSectionTaken: 'The section "%s" already exists in this source.',
  hbSectionsFull: 'The source already has %n sections - that is the limit.',
  hbCreateFailed: 'Could not create. Check the connection and try again.',
  hbWriteFailed: 'Could not save. Check the connection and try again.',
  hbBookChanged: 'The source was changed on another device. The data is updated - try again.',
  limitHbItems:
    'You have reached the limit of %n items of your own. Need more? Write to daggerheart.loot@gmail.com.',
  limitHbBooks:
    'You have reached the limit of %n sources. Need more? Write to daggerheart.loot@gmail.com.',
  hbRelations: 'Relations',
  hbLine: 'Upgrade line',
  hbLineHelp:
    'An upgrade line is one piece of equipment across tiers, for example a sword at tiers 1-4; the card draws a ladder of the tiers. "Unique" keeps the item out of a line; "In a line" adds the item as a rung of a line of the same equipment type; "New line" starts a line that your other items can join.',
  hbCraftIntoHelp:
    'Items that are made from this one: for example, an awakened weapon from a dormant one. These are not rungs of one line - use "Upgrade line" for those. The chosen item shows the link under "Made from".',
  hbCraftFromHelp:
    'Items this one is made from. The chosen item shows the link under "Upgrades to".',
  hbSetHelp:
    'A set is a group of items with a shared bonus. The card of each item in the set names the others and shows the bonus. Choose a set from the books or one of your own, or make one with "+ New set...".',
  hbRefsHelp:
    'A rule card is a rule the item refers to: a spell, a feature, an adversary. The item\'s card shows it as a folded block. Choose a card from the catalog or one of your own, or make one with "New rule card".',
  hbLineUnique: 'Unique',
  hbLineIn: 'In a line',
  hbLineNew: 'New line',
  hbLinePick: 'The line this item joins',
  hbFindLine: 'Find equipment in an upgrade line...',
  hbLineN: 'a line of %n tier|a line of %n tiers',
  hbLineAlone: 'A line with no other items',
  hbFindItem: 'Find an item by name...',
  hbFindMore: 'Add more: find an item...',
  hbFindCard: 'Find a card: a spell, a feature, an adversary...',
  hbPickFull: 'Already %n - that is the most',
  hbPickNone: 'Nothing found',
  hbPickMore: '%n more - narrow the search',
  hbRemove: 'Remove: %s',
  hbUpTo8: 'Up to 8 items.',
  hbRefs: 'Rule cards',
  hbRefsHint: 'Up to 3 cards.',
  hbGoneItem: 'This item no longer exists',
  hbGoneCard: 'This card no longer exists',
  hbSetNew: '+ New set...',
  hbNewSet: 'New set',
  hbNewCard: 'New rule card',
  hbSetName: 'Set name',
  hbSetBonus: 'Set bonus',
  hbCardName: 'Card name',
  hbCardSub: 'Subtitle',
  hbCardSubHint: 'Optional. For example: Sage · Level 1 · Spell.',
  hbCardText: 'Card text',
  hbCardUrl: 'Link',
  hbCardUrlHint: 'Optional: a page with the full text of the rule.',
  hbCreateSet: 'Create set',
  hbCreateCard: 'Create card',
  hbSetInlineHint:
    "The set is created at once, in this item's source, and chosen here; its bonus is stored once and shows on every item of the set.",
  hbCardInlineHint:
    "The card is created at once, in this item's source, and chosen here. An item holds up to 3 cards.",
  hbCardEditN:
    'Changes appear on %n item and in the lists that hold it.|Changes appear on %n items and in the lists that hold them.',
  hbErrSetBonus: 'Enter the set bonus.',
  hbErrCardText: 'Enter the card text.',
  hbErrUrl: 'A link starts with https:// and holds Latin characters with no spaces.',
  hbSetTaken: 'The set "%s" already exists.',
  hbCardTaken: 'The rule card "%s" already exists.',
  hbCardChanged: 'The card was changed on another device. The data is updated - try again.',
  hbCardGone: 'This card was deleted on another device.',
  hbSetCreated: 'Set "%s" created',
  hbCardCreated: 'Rule card "%s" created',
  hbErrLine: 'Choose an item of the line, or press "Unique".',
  hbErrLineType:
    'This line holds equipment of another type: choose another line, or press "Unique".',
  hbErrSetOpen: 'Create the set with "Create set", or press "Cancel".',
  hbErrCardOpen: 'Create the card with "Create card", or press "Cancel".',
  hbSourcesN: '%n source|%n sources',
  hbCards: 'Cards',
  hbSets: 'Sets',
  hbSetsN: '%n set|%n sets',
  hbRefsN: '%n rule card|%n rule cards',
  hbCardsN: '%n card|%n cards',
  hbNoSets: 'No sets yet.',
  hbNoRefs: 'No rule cards yet.',
  hbDeleteSet: 'Delete the set "%s"? This cannot be undone.',
  hbDeleteSetUsed:
    'Delete the set "%s"? It is named in %r - its name and bonus disappear there. This cannot be undone.',
  hbDeleteRef: 'Delete the rule card "%s"? This cannot be undone.',
  hbDeleteRefUsed:
    'Delete the rule card "%s"? It is named in %r - it disappears there. This cannot be undone.',
  hbSetDeleted: 'Set "%s" deleted',
  hbCardDeleted: 'Rule card "%s" deleted',
  hbItemsIn: '%n item|%n items',
  hbDeleteItemRel: 'The item "%s" is named in %r. Delete it? This cannot be undone.',
  hbDeleteItemInListsRel:
    'The item "%s" is in %l and named in %r. Delete it and remove it from the lists? This cannot be undone.',
  limitHbCards:
    'You have reached the limit of %n cards (sets and rule cards). Need more? Write to daggerheart.loot@gmail.com.',
  hbImport: 'Import items',
  hbImportHead: 'Import items from a JSON file',
  hbImportHintBefore: 'A file saved with "Download JSON" or written to the ',
  hbImportSchema: 'homebrew-v1 schema',
  hbImportHintAfter:
    '), or the ZIP archive from "Download my data". Items you already hold can be skipped or updated.',
  hbImportCounts: 'Sources: %b, sections: %s, cards: %c, items: %i.',
  hbImportHeld: 'Items and cards your account already holds: %n.',
  hbImportWhere: 'Where the items go',
  hbImportNoBook: 'No source',
  hbImportToHome: 'Into "Homebrew"',
  hbImportToHeld: 'Into "%s"',
  hbImportToFileNew: 'Into "%s" (new)',
  hbImportToNew: 'New source "%s"',
  hbImportNewName: 'New source name',
  hbImportNoteNew: 'The source is created with its sections: %n.',
  hbImportNoteKey: 'The source key matches yours: the items go into it.',
  hbImportNoteName:
    'A source of this name exists with another key (the file was made again). By default the items go into your source.',
  hbImportNoteAdd: 'Sections added to the source: %n.',
  hbImportNoteHome: '"Homebrew" has no sections: the items go in with no section.',
  hbImportSameNames:
    'Items with the same name already in your account: %n - they are added again',
  hbImportFull: '"%s" would hold more than 30 sections - choose another source.',
  hbImportMoreRows: 'and %n more source|and %n more sources',
  hbImportHeldLabel: 'Items, cards and sources you already hold',
  hbImportSkip: 'Skip',
  hbImportUpdate: 'Update',
  hbImportSkipNote: 'The items and cards you hold (%n) stay as they are; new ones are added.',
  hbImportUpdateNote:
    'The text and stats of the items and cards you hold (%n) are replaced from the file, and so are the source names. List references stay live; frozen copies do not change.',
  hbImportSkipBooksNote:
    'The names of the sources you hold stay as they are; new sections are added.',
  hbImportUpdateBooksNote:
    'The names of the sources you hold are replaced from the file; new sections are added.',
  hbImportUpdateConfirm:
    'Update the items and cards you hold (%n)? Their text and stats are replaced from the file. This cannot be undone.',
  hbImportPosBook: 'Source %n',
  hbImportPosCard: 'Card %n',
  hbImportPosItem: 'Item %n',
  hbImportUnknownRef:
    '%f "%v" - not in the file, your account or the catalog; the link is kept but draws nothing',
  hbImportKindDiffers: 'your account holds a card of the other kind under this key - skipped',
  hbImportErrName: 'no name - write en or ru',
  hbImportErrKey: 'key "%v" - hb_ and 16 characters of a-z, 2-7',
  hbImportErrKeyTwice: 'the key "%v" is already in the file',
  hbImportErrBook: 'no source "%v" in the file',
  hbImportErrSection: 'the item\'s source has no section "%v"',
  hbImportErrLine: 'eq.line - this line holds another equipment type',
  hbImportErrSelf: '%f - the item names itself',
  hbImportErrDmg: '%f "%v" - write damage as d8 or d10+2',
  hbImportErrControl: '%f - control characters',
  hbImportErrOrder: 'eq.th - the second threshold above the first',
  hbImportErrMany: '%f - more than %n values',
  hbImportErrType: '%f: wrong value type',
  hbImportErrEnum: '%f "%v": not an allowed value - check it against llms.txt',
  hbImportErrRange: '%f %v - out of range',
  hbImportErrPattern: '%f "%v": wrong format - check it against llms.txt',
  hbImportErrTwice: '%f - a value repeats',
  hbImportManyBooks: 'More than %n sources',
  hbImportManyCards: 'More than %n cards',
  hbImportManyItems: 'More than %n items',
  hbImportNotFile: 'Not an items file: no format field with daggerheart-loot/homebrew.',
  hbImportVersion: 'An items file of version %s: the site reads version 1.',
  hbImportNoVersion: 'The file has no version field. The site reads version 1.',
  hbImportEmpty: 'The file holds no sources, cards or items.',
  hbImportZipNone: 'The archive holds no homebrew.json.',
  hbImportZipMany: 'The archive holds several homebrew.json files: unzip it and choose one.',
  hbImportZipPacked:
    'Another program compressed this archive: unzip it and choose homebrew.json.',
  hbImportZipLists: "The archive's lists.json is imported on the My lists page.",
  hbImportDone: 'Items imported: %n',
  hbImportDoneUpdated: 'updated: %n',
  hbImportDoneSkipped: 'skipped: %n',
  hbImportDoneBooks: 'new sources: %n',
  hbImportDoneCards: 'new cards: %n',
  hbImportFailed: 'Could not import. Check the connection and try again.',
  hbImportRefused: 'The server refused the file. Reload the page and choose the file again.',
  hbImportChunkFailed: 'Could not load the import.',
  hbMove: 'Move (%n)',
  hbMoveGo: 'Move',
  hbMoving: 'Moving...',
  hbMoveHere: 'The ticked items are already here.',
  hbMovedN: 'Items moved: %n',
  hbMoveFailed: 'Could not move. Check the connection and try again.',
  hbMoveChanged: 'The items were changed on another device. The data is updated - try again.',
  hbMoveBookGone:
    'This source is gone - it was deleted on another device. Choose another source.',
  hbMoveSectionGone:
    'This section is gone - it was deleted on another device. Choose another section.',
  hbMoveRefused: 'The server refused the move. Reload the page and try again.',

  exportJson: 'Download JSON',
  exportOverBounds: 'This file cannot be imported whole.',
  exportBig: 'It is larger than 5 MB: export the lists in parts.',
  exportHomebrewBig:
    'The homebrew.json file is larger than 5 MB: download the sources one by one on the My items page.',
  exportManyLists: 'It holds more than 1000 lists: export them in parts.',
  exportLongLists: 'Lists with more than 5000 items: %s. Split those lists.',
  exportHomebrewSkippedN:
    '%n own item is not in the file: your account no longer holds it.|%n own items are not in the file: your account no longer holds them.',
  pickList: 'Select: %s',
  deleteListsConfirm:
    'Delete lists (%n): %s? Their player and GM links will stop working. This cannot be undone.',
  listsDeleted: 'Lists deleted: %n',
  andMore: 'and %n more',
  requestLinesMoreN: 'and %n more item|and %n more items',
  requestsMoreN: 'and %n more request|and %n more requests',
  requestLinesMax:
    'A request can hold at most %n item, and %k are ticked. Untick some and send again.|A request can hold at most %n items, and %k are ticked. Untick some and send again.',
  importOpen: 'Import from file',
  importHead: 'Import from a JSON file',
  importPick: 'Choose a file...',
  importHintBefore: 'A JSON file saved with "Download JSON" or written to the ',
  importSchema: 'import-v1 schema',
  importHintMid: ' (',
  importLlms: 'a description for AI assistants',
  importHintAfter:
    '), or the ZIP archive from "Download my data". The lists are added as new ones; the lists you have do not change.',
  importPreview: 'Lists: %l, items: %n.',
  importSkippedN: 'Items skipped: %n.',
  importWillN: '%n item will be imported|%n items will be imported',
  importListEmpty: 'no items',
  importNoName: '(no name)',
  importPos: 'Item %n',
  importSkipUnknown: 'skipped - the data has no such record',
  importSkipRepeat: 'skipped - already at item %n',
  importNameTaken: 'Your account already has a list with this name - there will be two',
  importZipOther: 'The archive holds files this version does not read: %s.',
  importGo: 'Import',
  importDone: 'Lists imported: %n',
  importTooBig: 'The file is larger than 5 MB.',
  importZipTooBig: 'The archive is larger than 10 MB.',
  importTooSlow: 'The file is too large for one import: split it into several.',
  importNotJson: 'This is not a JSON file.',
  importNotBundle:
    'This is not a lists file: it has no "format" field with the value daggerheart-loot/lists.',
  importVersion: 'Unknown format version: %s. The app reads versions 1 and 2.',
  importNoVersion: 'The file has no "version" field. The app reads versions 1 and 2.',
  importEmpty: 'The file holds no lists.',
  importZipNoLists: 'The archive has no lists.json.',
  importZipManyLists:
    'The archive holds more than one lists.json: unzip it and choose the one you need.',
  importZipPacked: 'Another program compressed this archive: unzip it and choose lists.json.',
  importZipHomebrew: "The archive's homebrew.json is imported on the My items page.",
  importRefused:
    'The server refused the file: your account\'s data changed. Press "Import" again.',
  importFrozenN:
    'Own items your account does not hold: %n - they are kept as copies. To keep them live, import the items on the My items page first.',
  importMoreLists: 'and %n more list|and %n more lists',
  importNotZip: 'This is not a data archive.',
  importErrors:
    'The file has errors - nothing was imported. Fix them and choose the file again.',
  importFieldName: 'Name',
  importErrMissing: '%f: a required field is missing',
  importErrName: 'Name: empty or missing',
  importErrType: '%f "%v": wrong type - expected %s',
  importErrNotObject: '"%v": wrong type - expected a JSON object',
  importErrId:
    'id "%v": not a record id - Latin letters, digits, _ and - only, up to 64 characters',
  importErrHbId: 'id "%v": not an own item key - hb_ and 16 characters of a-z, 2-7',
  importErrSnapshot: 'snapshot: not a copy of an item - check its fields against llms.txt',
  importErrLong: '%f: longer than %n characters',
  importErrRange: '%f %v - out of the range %s',
  importErrEnum: '%f "%v": allowed values - %s',
  importErrExtra: 'unknown field %f',
  importErrManyLists: 'More than %n lists',
  importErrManyEntries: 'More than %n items',
  importErrMoreList: '...and %n more in this list',
  importErrMore: '...and %n more error|...and %n more errors',

  shareLinkPlayers: "Players' link",
  shareLinkGm: "GM's link",
  shareCopy: 'Copy',
  shareCreate: 'Create link',
  shareDelete: 'Delete link',
  shareStopped: 'Link deleted',
  shareHint:
    '"Delete link" ends access: a deleted link no longer opens the list. "Create link" makes a new one. The GM\'s link also shows the "GM only" notes - give it to GMs only.',
  shareLoadFailed: 'Could not load the links.',
  shareCreated: 'Link created.',
  shareDeleted: 'Link deleted: it no longer opens the list.',
  shareFailed: 'Could not change the link. Check the connection and try again.',
  gmShareCopied: "GM's link copied - it carries the GM notes",
  updatedAgo: 'Updated %s',
  updatedNow: 'Updated just now',
  ownList: 'This is your list.',
  ownListEdit: 'Open to edit',
  shareGone: 'This list is no longer available',
  shareGoneSub: 'The owner deleted this link or the list.',
  sharedFailed: 'The list did not load',
  sharedFailedSub: 'Check the connection and press "Retry".',
  listUpdated: 'The list was updated',
  cloneFailed: 'Could not save the list to your lists. Check the connection and try again.',
  legacyLinks:
    'Links like this one (#/l/) stop opening on %d. Save the list to your lists to keep it.',

  requestSend: 'Notify the owner',
  requestSending: 'Sending...',
  requestSentDone: 'Request sent',
  requestSent: "The request was sent to the list's owner.",
  requestSentOwner: 'The owner got the request.',
  requestRate: 'Too many requests through this link: wait a minute.',
  requestPending: 'The owner already has %s with no answer. Try again later.',
  requestsN: '%n request|%n requests',
  requestStale: 'The list has changed. Check your choice and send again.',
  requestNetwork: 'Could not send. Check the connection and try again.',
  requestRefused: 'The server did not accept the request.',
  notifyQuestion: "Tell the list's owner that you took these items?",
  notifyYes: 'Notify',
  notifyRemember: 'Remember the answer',
  requestsHead: 'Requests (%n)',
  requestByPlayers: "Through the players' link",
  requestByGm: 'Through the GM link',
  requestJustNow: 'just now',
  requestExpires: 'expires %s',
  requestOf: '×%w of %h',
  requestNotInList: 'not in the list',
  requestApply: 'Apply',
  requestApplyAvailable: 'Apply what is there',
  requestDecline: 'Decline',
  requestShort: 'Not enough: %s. Nothing was taken.',
  requestShortLine: '%s - asked %w, have %h',
  requestsDecided: 'Decided this time (%n)',
  requestsHide: 'Hide',
  requestsHideName: 'Hide the decided requests',
  requestAppliedLine: 'applied',
  requestTakenLine: 'applied: %n taken',
  requestDeclinedLine: 'declined',
  requestApplied: 'Request applied',
  requestTaken: 'Request applied: %n taken',
  requestDeclined: 'Request declined',
  requestDecidedElsewhere: 'This request was already decided on another device.',
  requestExpired: 'This request has expired: an hour passed with no answer.',
  requestActFailed: 'Could not answer the request. Check the connection and try again.',
  requestNew: 'New request',
  requestsWaitN: '%n request waits for an answer|%n requests wait for an answer',

  quoted: '"%s"',
  movedNotice: 'Lists from this browser were moved to your account: %s.',
  movedBad:
    'This browser still holds a damaged copy of your lists: it could not be read or moved. If it held something important, write to daggerheart.loot@gmail.com.',
  moving: 'Moving your lists to your account...',
  moveFailed: 'Not every list was moved: no connection. We will try again next time.',
  moveAttention: 'Not moved: %s.',
  moveAttentionWhy: 'The server did not take the list. Write to daggerheart.loot@gmail.com.',
  moveHeldWhy:
    'The copy in your account did not match the list. Write to daggerheart.loot@gmail.com.',
  localOnlyMove:
    'Sign in before %d and they move to your account. After that date the app stops showing them.',
  moveBannerLead: 'Your lists are stored only in this browser.',
  moveBannerSignIn: 'Sign in and move the lists',
  moveBannerHide: 'Dismiss the reminder',
  localReadOnlyTitle: 'Lists in this browser are read-only from %d.',
  localReadOnly:
    'Sign in and they move to your account, where you can edit them again. Copying the text and printing still work.',
  linkRetired: 'Links of this kind stopped opening on %d.',
  linkRetiredSub: 'Ask the sender for a new link, or sign in to build a list.'
};

/* The texts that name the cutoff take its date from the one constant. */
const DATED: readonly (keyof Dict)[] = [
  'legacyLinks',
  'localOnlyMove',
  'localReadOnlyTitle',
  'linkRetired'
];

function dated(d: Dict, lang: Lang): Dict {
  const out: Dict = { ...d };
  for (const k of DATED) out[k] = d[k].replace('%d', legacyDateText(lang));
  return out;
}

const DICTS: Record<Lang, Dict> = { ru: dated(ru, 'ru'), en: dated(en, 'en') };

export function dict(lang: Lang): Dict {
  return DICTS[lang];
}

/** Which dictionary key names a section, for the tab title
 *  (`<section label> — <docTitle>`). Mirrors `TabBar.svelte`'s own `TABS`
 *  pairing exactly - the exhaustive `Record<Section, ...>` is what keeps the
 *  two from drifting apart the moment a tenth section arrives. */
export const SECTION_LABEL: Record<Section, keyof Dict> = {
  'roll/std': 'std',
  'roll/alt': 'alt',
  'roll/wondrous': 'wondrous',
  'roll/dread': 'dread',
  'roll/voa': 'voa',
  'roll/dv': 'dv',
  'roll/community': 'community',
  tables: 'tables',
  lists: 'lists',
  search: 'search'
};
